### ISSUE TITLE
No translate not working in Firefox ESR 68.4.2

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#1012]

**Comment by svenseeberg** [comment]
Cannot be reproduced.

**Comment by svenseeberg** [comment]
@FritjofK can you find out which page / paragraph should be marked as not translatable?

**Comment by FritjofK** [comment]
I do not have a specific page but it did not work in any case. 
They wanted to prepare DeepL-Translations, so they tried to tag an adress. I think when they clicked the "Update" Button it just did not save the tag and everything stayed the same.

**Comment by svenseeberg** [comment]
I still cannot reproduce this. Closing this for now.
