### ISSUE TITLE
Display error with push news log in CMS

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#1014]
see the attached picture. The "Danke für das Vertrauen in WordPress" should not be crossing the history log.

**Comment by dkehne** [comment]
![issue](https://user-images.githubusercontent.com/4182469/74658243-21a8b100-5192-11ea-8583-bfa663851aaf.PNG)

**Comment by svenseeberg** [comment]
@dkehne can you please share your Firefox version?  Seems to work on version 73.

**Comment by dkehne** [comment]
i have 73.0.1 and i just looked it up in testumgebung
