### ISSUE TITLE
Renaming inside the Feedback-function

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#1015]
When users leave feedback for the whole Integreat-App it is shown to the cities as feedback to the page "Verfügbare Kategorien". This is not intuitive and should be renamed to "Integreat allgemein" or "Gesamte Integreat-App". 
![Unbenannt](https://user-images.githubusercontent.com/4182469/74658355-60d70200-5192-11ea-87f8-6d821e093607.PNG)

**Comment by svenseeberg** [comment]
Well, it is supposed to be feedback on the main menu (6+2). What about "Hauptmenü / Integreat Allgemein"?

**Comment by dkehne** [comment]
would be okay as well :)
