### ISSUE TITLE
"WPML" im Menü umbenennen in "Sprachen"

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#104]
Der Standard Benutzer kennt WPML nicht, daher ein allgemein gebräuchliches Wort verwenden.

Mehrsprachigkeit beachten (Stichwort pot-Dateien), den Menüpunkt könnten auch Übersetzer sehen, die WordPress auf Englisch (etc.) eingestellt haben.

**Comment by Meash** [comment]
WPML Support Anfrage: https://wpml.org/forums/topic/rename-wpmls-menu-label-to-language-settings/

**Comment by Meash** [comment]
Antwort Support: Übersetzt es doch einfach anders

**Comment by sascha11110** [comment]
Für die Anpassung von Sprachdateien eignet sich das Plugin "Loco Translate"
ganz gut...

Martin Schrimpf <notifications@github.com> schrieb am Mi., 25. Nov. 2015 um
14:46 Uhr:

**Comment by Lemming0815** [comment]
wer hat die account informationen für wpml? Ich müsste mich da einloggen, um Übersetzungen für dfie Themes runterzuladen

**Comment by Lemming0815** [comment]
Ich schlage statt "Sprachen" "Übersetzung" vor als Stringersatz für WPML

**Comment by Meash** [comment]
Passt auch.

**Comment by dkehne** [comment]
@Lemming0815 : Martin wie weit bist du hier? Thema ist seit 1 Monat offen. Kannst du das umsetzen diese Woche oder das Thema übergeben?

**Comment by sven15** [comment]
Not needed. Verwalter verstehen das auch so.
