### ISSUE TITLE
Mobile Preview: Text-Bündigkeit von Android übernehmen

### ISSUE THREAD

**Issue by julia-goetz** [Integreat/cms#106]
Android macht z.B arabischen Text automatisch rechtsbündig, die Mobile Preview soll das selbe machen

(Kommentar Martin: ursprünglicher Text below)
Überschriften sind nur linksbündig, müsste für Arabisch mit einstellbar sein

**Comment by dkehne** [comment]
Habs getestet. Passiert aktuell so - arabisch ist rechtsbündig. Nice! Bei Farsi allerdings noch nicht der Fall. @Meash soll ich dafür nen eigenes Issue aufmachen oder ist das schnell behoben?

**Comment by Meash** [comment]
Keine Ahnung, warum Arabisch geht :D Prinzipiell wäre eine Lösung schön, die automatisch alles so anzeigt wie auf dem Handy - dafür bräuchte man aber wohl einen Emulator, ergo unrealistisch. Farsi gehört auch zu diesem Issue, geht ja um alle Sprachen.

**Comment by sven15** [comment]
Solved with WP RTL.
