### ISSUE TITLE
"Sichtbarkeit" aus Seitenbearbeitung entfernen

### ISSUE THREAD

**Issue by Dalanie** [Integreat/cms#109]
Stell ich die Sichtbarkeit auf Privat und mach einen neuen Request mit der Zeit, erwarte ich, diese als "Trash" oder irgendwas zu bekommen. Leider bekomme ich nichts.

Stell ich die Sichtbarkeit auf Öffentlich, bekomme ich witzigerweise diese Änderung.

**Comment by Meash** [comment]
duplicate of #244
