### ISSUE TITLE
Unterschied Globale/Lokale Info

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#11]
Anfrage von Wiesche: Ist es sinnvoll ist, dass wir schon den Unterschied global/lokale Information, Quelle (idealerweise Link auf Institution), Datum, Sprachen pflegen können, um später nicht alles nachzuarbeiten?

**Comment by dkehne** [comment]
Oh yeah. Das wird nochmal spannend Mitte 2016. :)

**Comment by sven15** [comment]
Is this resolved with #361? I suggest yes.

**Comment by Meash** [comment]
Agree.
