### ISSUE TITLE
Unterstrichene Texte, aber kein Unterstreichen-Button

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#110]
![unbenannt](https://cloud.githubusercontent.com/assets/4182469/10871528/39d79eb2-80ea-11e5-81d9-013d4a49b3de.PNG)

**Comment by pblanz** [comment]
Ich denke das hier kann geschlossen werden, da sich in #244 darum gekümmert wird.

**Comment by dkehne** [comment]
Ja passt!
