### ISSUE TITLE
Unvollständige Tabellen bei Pdf-Creator

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#111]
Scheinbar Probleme mit Tabellen. Siehe Kleidung&Lebensmittel in Augsburg Instanz
![unbenannt](https://cloud.githubusercontent.com/assets/4182469/10871582/448aeca0-80eb-11e5-99cd-b2e2e139905a.PNG)

**Comment by pblanz** [comment]
Ich vermute mal, das hier das Problem ist, das die Tabelle sehr lang ist und nicht auf eine Seite passt und der PDF-Creator die Tabelle nicht ordentlich splitten kann.

**Comment by pblanz** [comment]
das problem war doch ein anderes. Wordpress benutzt aus Gründen der Formatierung <p> tags in tabellenzellen. pdf-creator-lite lässt regex's über den html-source-code laufen, die (warum auch immer) manche öffnende <p> tags in tabellenzellen entfernen. Ich hab jetzt mal nen schnellen fix geschrieben, der einfach alle <p> tags (öffnend und schließend) aus den tabellen entfernt. Die formatierung ist danach immer noch in Ordnung.

**Comment by Meash** [comment]
@dkehne kannst du auf dem [Testsystem](http://vmkrcmar21.informatik.tu-muenchen.de/wordpress_test/augsburg/wp-admin/tools.php?page=exportAsPDF) checken, ob es so passt?

**Comment by dkehne** [comment]
Ich prüfe das.

**Comment by dkehne** [comment]
Big Applause Pirmin!!! Läuft. Keine Probleme mehr damit (im Testsystem).

:) @Meash: Wann closen wir? Nach transport ins live?
