### ISSUE TITLE
Abgelaufene Events ausblenden und chronologisch korrekte Reihung bei wiederkehrenden Events

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#112]
Abgelaufene Events sollen zukünftig nicht mehr angezeigt werden, insofern Sie in der Vergangenheit liegen und es sich nicht um wiederholende Events handelt. Falls es wiederkehrende Events sind, sollen sie selbstverständlich chronologisch in der richtigen Reihenfolge gereiht sein.

**Comment by dkehne** [comment]
Passt so. Ist erfolgt!
