### ISSUE TITLE
WPML Translation Management

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#113]
WPML Translation Management unter die Lupe nehmen:

* kann man damit Aufträge für Übersetzungen erstellen
* brauchen die Übersetzer gesonderte Nutzer
* wie einfach ist das Übersetzen?
  * sehe ich die Original Inhalte zum Vergleich? (Feedback von @elordin: nebeneinander anzeigen ist am besten)

**Comment by benginoe** [comment]
@Meash können wir das Plugin mal installieren auf einer weiteren Wordpress-Test-Instanz, das Plugin würde einiges erleichtern soweit ich es nun recherchiert habe.

**Comment by Meash** [comment]
Sure, schau mal, ob du dich auf /wordpress_test anmelden kannst.

**Comment by benginoe** [comment]
@Meash leider nein, erweiter bitte meine rechte, sodass ich das Plugin installieren kann und in der Augsburg Instanz ausreichend testen kann.

**Comment by Meash** [comment]
Hast.

**Comment by dkehne** [comment]
Leute ich brauche das Translation Management endlich, sonst können wir nicht über die XLIFF-Schnittstelle übersetzen lassen. Das muss bis heute Abend soweit stehen, damit ich den Auftrag für Persisch noch rausfeuern kann!

https://wpml.org/de/documentation-3/ubersetzen-ihrer-inhalte/verwendung-von-desktop-cat-tools/

@benginoe

**Comment by dkehne** [comment]
Tolingo hat uns eine Anleitung zur Verfügung gestellt:

[tolingo_WordPress_export anleitung_2015-08-17.pdf](https://github.com/Integreat/cms/files/43697/tolingo_WordPress_export.anleitung_2015-08-17.pdf)

**Comment by dkehne** [comment]
@benginoe das sieht laut Anleitung nach 30 min Arbeit aus. Warum ist das Issue seit 7 Tagen offen?

**Comment by dkehne** [comment]
@Meash Bitte auch in der Live-Version das Translation Management aktivieren :) Hab in Test-Umgebung getestet, allerdings fehlt der XLIFF-Export Button. Kann es sein dass auf der Testinstanz nicht alle Features vorhanden sind wie bei der Version des 79$-WPML Plugins? Oder läuft das auf beiden WP-Systemen?

**Comment by benginoe** [comment]
Das ist mir bisher auch nicht klar geworden, ich kontaktiere deswegen noch mal den Support, ich hab aktuell mich eher auf ein anderes Ticket konzentrietr und dachte, dass das nur ein nice to have ist. Sry. hab die Prio High übersehen.

**Comment by Meash** [comment]
Test = live, da ist kein Unterschied bei den Versionen. Test ist nur early
access ;)

**Comment by dkehne** [comment]
Gibts hier Logins für den WPML Support @Meash ?

**Comment by dkehne** [comment]
Okay ich lese wieder nicht richtig.... liegt im Drive. Alright.

**Comment by Meash** [comment]
Support Anfrage: https://wpml.org/forums/topic/xliff-export-not-available/

**Comment by Meash** [comment]
Geklärt. Export Button ist unter WPML > Übersetzungen.
