### ISSUE TITLE
Web Ansicht

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#114]
Responsive Ansicht der Inhalte in Web-Frontend.
Automatisch für alle Multisites.

FYI: In Augsburg und Werne sind die Front-Ansichten derzeit customized, sodass Seiten statt Beiträgen angezeigt werden. Evtl muss man die Standard Customization anpassen und diese beiden Seiten zurücksetzen.

**Comment by Meash** [comment]
Wie ist das mit dem Customizer? Muss man sich den für sein Theme selber bauen?

**Comment by sascha11110** [comment]
Was meinst du mit Customizer? Options Page? Oder "Anpassen" unter Design?

Martin Schrimpf <notifications@github.com> schrieb am Mo., 14. Dez. 2015
00:06:

**Comment by Meash** [comment]
Zweiteres, "anpassen"

**Comment by sascha11110** [comment]
WordPress Standardfunktion. Aber muss man halt für jedes Themen anpassen.
Wird von der App daraus noch was außer dem Bild gezogen?

Martin Schrimpf <notifications@github.com> schrieb am Mo., 14. Dez. 2015
00:35:

**Comment by Meash** [comment]
Icon und header image. Mittelfristig sollte eine Stadt auch ihre Farbe
einstellen können, die wird in der App mit angezeigt (und dann vlt auch in
der Web Ansicht?)
Am 14.12.2015 00:43 schrieb "sascha11110" <notifications@github.com>:

**Comment by Meash** [comment]
Wie ist der Stand @sascha11110?

**Comment by sascha11110** [comment]
Mehrsprachigkeit, Anpassungen des Themes (z.B. eigene Farbe) und SuFu 
fehlt. Plan ist, bis zur Konferenz eine Version fertig zu machen, die 
man dann diskutieren kann.

Am 13.02.2016 um 14:46 schrieb Martin Schrimpf:

**Comment by Meash** [comment]
> Plan ist, bis zur Konferenz eine Version fertig zu machen, die man dann
diskutieren kann.

Klingt gut!

**Comment by sascha11110** [comment]
Wie wird denn in der App die "Front Page" gefunden? Die erste in der Baumstruktur? In Wordpress gibt's da ja eigentlich standardmäßig ein Feld zur Auswahl einer statischen Front Page

**Comment by Meash** [comment]
Finde alle Varianten gut, können auch das Stadt Bild anzeigen. Diskussion
dann auf der Konferenz ^^

**Comment by Meash** [comment]
resolved in #345
