### ISSUE TITLE
Klickguide Tutorial

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#116]
Initiale Nutzer-Einführung in das System, z.B. für Frau Haase in Bad Tölz.

Laut @sascha11110 gibt es dafür ein Plugin

**Comment by sascha11110** [comment]
Add functionality for creating a PDF document of the whole guide / of specific tours

**Comment by dkehne** [comment]
@sascha11110 gibts hier schon was Neues?

**Comment by sascha11110** [comment]
Siehe #146

Daniel Kehne <notifications@github.com> schrieb am Di., 12. Jan. 2016 00:40:

**Comment by sascha11110** [comment]
Solved by #282.
