### ISSUE TITLE
Video Kurzvorstellung

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#117]
Für neue Städte zum Zeigen bei der Einführung, bevor sie ein System haben. Kurze Übersicht über das Projekt.

@benginoe -> Malek

**Comment by benginoe** [comment]
Aktuell eher schwierig mit dem Menschen mit dem ich es eigentlich vor hatte, hierzu etwas umzusetzen...

Bin aktuell auf der Suche nach anderen Menschen die uns soetwas erstellen können.

**Comment by Meash** [comment]
Migriere das hier mal ins Orga Repo
