### ISSUE TITLE
URL Management

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#119]
Pretty URLs

**Comment by benginoe** [comment]
Wie wollen wir bei Städten mit gleichem Namen verfahren und mit Umlauten aus anderen Sprachen?

**Comment by Dalanie** [comment]
frankfurt, frankfurtanderoder

**Comment by benginoe** [comment]
@Meash können wir beim erstellen einer neuen Instanz ein Script auf dem Server triggern lassen? Woraus werden die Rückgaben bspw. von /wordpress/wp-json/extensions/v0/multisites/ erstellt? hier muss man sehr wrsl auch noch Dinge ändern.

Stand:

Datenbank:
Aktuell noch am prüfen ob spezielle Vorkehrungen in der Datenbank vorgenommen werden müssen.

Grundsätzliche Vhostdatei steht
-Erstellen in APACHECONFIGPATHAVAILABLE = "/etc/apache2/sites-available/"
- Linken nach APACHECONFIGPATHENABLED = "/etc/apache2/sites-enabled/"
- (Bin gerade noch dran einen weiterleitung auf virtuelle Verzeichniss zu machen. "/augsburg/de/", bin mir nicht ganz sicher ob das so klappt wie ich es mir vorstelle.)
augsburg.integreat-app.de -> augsburg.integreat-app.de/augsburg/de/


Regex: Scheint zu funktionieren, würde ich aber noch genauer Testen wollen.

SSL: pauschale Aktivierung: Wildcard-Zertifikat wäre zu bevorzugen, weil dann keine speziellen einrichtungen nötig sind und nicht immer ein eigenes Zertifikat erstellt oder Bezogen werden muss (wäre also eher gegen Let's Encrypt, weil es eine weitere Baustelle wäre und aktuell es immer noch ungewiss ist, wann release ist und wie die Umsetzung im Detail aussieht. @sven15  Hast du hier mehr Informationen) 
Soll hier immer auf https umgeleitet werden?


@dkehne Was soll die Standartsprache sein auf die verwiesen wird? (de // en wäre meine Wahl, oder was eigentlich noch besser wäre:eine Auswahl findet statt, wonach auf die gewünschte Sprache verwiesen wird + Cookie.)

(kurzer allgemeine Rückfrage Daniel ist dir klar, dass es SEO-Technisch suboptimal ist Subdomains zu nutzen, Seperate Seiten -> Seperates Ranking)

**Comment by mwi-tum** [comment]
das klingt super (vor allem weil ich nur die Hälte verstehe! :)
Was ich cool fände ist, wenn wir das CMS unter wunderland.intergreat-app.de erreichbar machen. Das Wordpress webfrontend können wir dann unter wunderland.intergreat-app.de/webapp laufen lassen, weil jede Stadt das dann hoffentlich unter wunderland.de/integreat laufen lässt. 
Wenn dazu noch eine generierte Begrüßungsmail an den ersten User käme die quasi auf das Backend und die Kurzanleitung von @sven15 referenziert wäre das ein super Willkommenspaket.

**Comment by dkehne** [comment]
Ich sehe das so wie @mwi-tum . Dann müssen wir die aktuellen CMS Pfade auch nicht umschupsen, sondern können die webapp als Subfolder aufrufen. Sven, können wir das so umsetzen im URL-Management @sven15 ?

**Comment by benginoe** [comment]
Ich hab hierzu bereits ein Skript in Bash geschrieben, schreibe es gerade in Python um, habe aber kleinere Probleme mit Regex ... Falls jemand hier unterstützen könnte, wäre es ziemlich cool.

Bestpractice zum erstellen von den Subdomains wäre, wenn das CMS, beim erstellen einer Instanz ein Python-Script anstupsen kann. Dieses erstellt dann automatisch die entsprechenden Vhost-Dateien und erstellt den "Link" zum SSL-Zertifikat. 

Hängt mit: https://github.com/Integreat/orga/issues/13 und https://github.com/Integreat/orga/issues/3 zusammen

**Comment by sven15** [comment]
Example configuration available: https://github.com/Integreat/cms/wiki/Load-Balancing-configuration

**Comment by sven15** [comment]
Currently any arbitrary subdomain links to the login screen. We can implement a /web/lang/ redirect to the content at some point. However I'm going to close this issue for now.
