### ISSUE TITLE
Web Ansichten aus Landing Page verlinken

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#121]
Aufbauend auf #114 die Web Ansichten der einzelnen Städte im Slider "In diesen Kommunen sind wir bereits aktiv" verlinken.

**Comment by dkehne** [comment]
Müssen wir uns nochwas überlegen, wenn es so viele Städte werden. Eventuell können wir einen eigene Seite "Partner" machen.

**Comment by sven15** [comment]
In Anbetracht der Tatsache, dass wir das neue Design bald life schalten können, wird dieses Thema aktuell.

**Comment by sven15** [comment]
waiting for deployment of #345

**Comment by Meash** [comment]
it's not implemented yet though, right?

**Comment by sascha11110** [comment]
Right. Will be done shortly

Am 27.04.2016 um 20:05 schrieb Martin Schrimpf:

**Comment by sven15** [comment]
We need an JS script which fetches all instances from the REST API with images and displays them on the landing page.

**Comment by sven15** [comment]
i think we do not need this. the list would become to large?! @dkehne @FritjofK

**Comment by dkehne** [comment]
Mhh mhhh. Link might be enough. There are more issues with higher priorities - so close it perhabs.
