### ISSUE TITLE
Pootle evaluieren

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#128]
"Get your community translating your software into their languages."
Im Namen von Manuel bitte um Prüfung des Online-Translationtool Pootle, welches frei zugänglich ist und in Phyton geschrieben wurde.

http://pootle.translatehouse.org/

Macht es Sinn, dass bei uns einzusetzen?

**Comment by Meash** [comment]
Geht es um eine Software/Pluginbarkeits-Prüfung? Falls nein, verschieb das bitte in orga, um festzustellen, ob wir pootle (o.ä.) prinzipiell einsetzen wollen oder WPML Translation Mgmt reicht

**Comment by dkehne** [comment]
Brauchen wir nicht mehr. Wir machen WPML Userrolle "Translator".
