### ISSUE TITLE
Monitoring aller (Web-)Services

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#136]
Monitoring/Überwachung ob alle Dienste erreichbar sind.

API für Mobileapp
Homepage
einzelne Städte
FTP-Backupsspace
Server

**Comment by dkehne** [comment]
@benginoe War das nur eine Idee oder läuft das oder hast du noch Input für uns?

**Comment by sven15** [comment]
Da wir zunehmend Nutzer haben, wir Monitoring schon aktuell. Wir sollten zumindest eine rudimentäre Form zeitnah auf die Reihe bekommen (und wenn es Ping von einem anderen Server mit automatischen Mails ist).

**Comment by sven15** [comment]
https://vmkrcmar80.informatik.tu-muenchen.de/nagios3/

**Comment by sven15** [comment]
We need Nagios scripts for the different services.
