### ISSUE TITLE
Automatische Aktivierung von neuen (merge) Plugins

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#138]

**Comment by Meash** [comment]
Evtl helfen uns must-use plugins: https://codex.wordpress.org/Must_Use_Plugins

**Comment by dkehne** [comment]
@sascha11110 Wie kommen wir hier voran? Was muss getan werden?

**Comment by sascha11110** [comment]
Da bin ich leider nicht im Thema

Daniel Kehne <notifications@github.com> schrieb am Di., 12. Jan. 2016 00:47:
