### ISSUE TITLE
Sachen aus functions.php in Plugin auslagern

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#139]

**Comment by dkehne** [comment]
Ist das ein potentieller Quick-Win? Wer kann hier übernehmen? @sascha11110 @pblanz @dwsoto ?

**Comment by sascha11110** [comment]
Bezieht sich das auf die WebView? Dann erledigt sich das m.E. mit der
Neugestaltung der WebView

Daniel Kehne <notifications@github.com> schrieb am Di., 12. Jan. 2016 00:48:

**Comment by Meash** [comment]
AFAIK hatte jemand Code in die `functions.php` gepackt, was bei der I1K dis-encouraged wurde. Habe jetzt auf die Schnelle aber nichts gefunden - wenn sich die Woche keiner mehr meldet, würde ich entsprechend closen.

**Comment by sven15** [comment]
In welcher functions.php war das denn? Scheint aus meiner Perspektive nicht mehr relevant.
