### ISSUE TITLE
WPML Flaggen in Baumstruktur einbauen

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#140]
Wa war die getroffene Absprache mit Thomas?

**Comment by dkehne** [comment]
Ja bitte einbauen. Also zumindest sollte es oben in der Headline stehen. Hinter den jeweiligen Seiten sind dann die Plus/Stift-Symbole. Das ist quasi verlinkt mit https://github.com/Integreat/cms/issues/137

**Comment by sven15** [comment]
Ähm was ist hier gemeint? In der Seitenübersicht ist dafür kein Platz, die Baumstruktur ist sowieso nach Sprache gefiltert? Im Edit ist das eine kleine, übersichtliche Tabelle? Bitte neu öffnen, falls wir das doch noch brauchen @dkehne
