### ISSUE TITLE
Bug bei Änderung der Reihenfolge in der Baumstruktur

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#141]
"teilweise muss man viermal ziehen, bis sich die Reihenfolge tatsächlich ändert"

**Comment by dkehne** [comment]
Das ist korrekt! Hier brauchen wir Abhilfe. Wer auch immer das liest, kann sich das Issue schnappen. Am besten weiß vermutlich @dwsoto Bescheid, woran das liegen könnte. Any Ideas?

**Comment by sven15** [comment]
Ich würde behaupten, dass das an frickeligem JS / UI / Pixelzuordnung liegt. Im Kern sollte das Problem ziemlich sicher im JS Code stecken.

**Comment by sven15** [comment]
We did not receive any complaints from users. It seems that this is of no bigger concern.

**Comment by dkehne** [comment]
Because we say to them Do NOT use the structure to change the order because it's buggy.

**Comment by sven15** [comment]
Okay, then we need to fix this upstream.

**Comment by Ponitac** [comment]
Fixed by Upgrading CMS Tree View. They seemed to fixed this by themselves :)

**Comment by Ponitac** [comment]
CMS Tree Plugin only fixes UI Bug, but does not affect WPML-structure

**Comment by svenseeberg** [comment]
WONTFIX
