### ISSUE TITLE
Push-Benachrichtigungen umbenennen

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#142]
weitere?

EDIT by Martin: WPML Renaming steht bereits in Issue #104

**Comment by Lemming0815** [comment]
push Benachritigungen ist eigentlich ein stehender Begriff für genau das.
Blöd nur, dass im Amt das viele nicht kennen. Die würden aber auch mit allen anderen hier erwähnten Varianten nichts anfangen können.

**Comment by dkehne** [comment]
Wir bleiben bei Push-Benachrichtigung!
