### ISSUE TITLE
Automatische Übersetzungen in Seitenübersicht kennzeichnen

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#144]
Im `post_meta` gibt es bei automatischen Übersetzungen einen Eintrag `automatic_translation = 1`. 
Wenn dieser `=1` ist, soll bei der Übersicht der Sprachen eine Kennzeichnung angezeigt werden (z.B. ein kleines `A` bei der Flagge?).

**Comment by dkehne** [comment]
Wird gekennzeichnet durch den Satz "Automatic Translation..."

**Comment by Meash** [comment]
Noch nicht im UI/der Anzeige.

**Comment by dkehne** [comment]
Kannst du das mal Mockupen @Meash ? Dann können wir das entsprechend jemandem assignen.

**Comment by svenseeberg** [comment]
We don't have automatic translations anymore.
