### ISSUE TITLE
Features je Instanz einstellbar machen

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#145]
(z.B. PDF Creator) >> ist eine abgespeckte Plugin-Verwaltung

**Comment by dkehne** [comment]
Das wird noch extrem wichtig. Welche Instanz dabei welches Feature auch tatsächlich aktivieren kann, wird aus der Masterinstanz bzw. NEtzwerk heraus geregelt. Ansonsten ist das Feature ausgegraut oder nicht vorhanden zum Klicken. Wird ne größere Aufgabe....

**Comment by Meash** [comment]
-> Plugin System

**Comment by dkehne** [comment]
Kann der Verwalter das? Kann er z.B. jetzt PDF oder Push-Nachrichten ohne große Schulung von uns an und aus schalten?

**Comment by sascha11110** [comment]
So wie ich das sehe hat die Rolle Verwalter keine Berechtigung auf die
Plugin Verwaltung zuzugreifen

Daniel Kehne <notifications@github.com> schrieb am So., 17. Jan. 2016 22:25:

**Comment by Meash** [comment]
Nein noch nicht, aber noch gibt es auch keinen konkreten Plan, wer was können soll. Sobald das verfeinert ist, können wir dazu ein spezifisches issue aufmachen.
