### ISSUE TITLE
Hilfe Button und Unterseite

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#146]
>> Verlinkung des Handbuchs
>> Aktivierung des Klickguides
>> eventuell Video

**Comment by Meash** [comment]
Das soll afaik in den WordPress Hilfe Button oben rechts integriert werden.

**Comment by dkehne** [comment]
@sascha11110 kannst du hier nochmal ausführender was zu schreiben oder aktuellen stand durchgeben?

**Comment by sascha11110** [comment]
Musste seit Ende Dezember paar Arbeiten fürs Zweitstudium fertig machen.
Bin eigentlich soweit, dass ich die einzelnen Boxen für die
Erklärungsschritte nur noch richtig per JavaScript positionieren muss.
Vielleicht habe ich am Wochenende etwas Zeit sonst ab Montag. Die
Verlinkung zum Guide hatte ich bisher in die WP Toolbar gepackt. Kann ich
meinetwegen auch in den Hilfe Button packen, aber in glaube der wird nicht
auf allen Seiten angezeigt

Daniel Kehne <notifications@github.com> schrieb am Di., 12. Jan. 2016 00:56:

**Comment by sascha11110** [comment]
Folgendes Problem: Der Hilfe-Button ist nur in den "Standard-Ansichten" von Wordpress zu sehen. Daher nicht in unserer Baumansicht der Seiten und unter Events. 

Bevor wird den ClickGuide nutzen können, müssen wir den Hilfe-Button überall integrieren. Legen wir in Zukunft neue Ansichten (z.B. post types) an, müssen wir darauf achten.

**Comment by Meash** [comment]
Gibt's keine Möglichkeit, den standardmäßig für alle Ansichten zu integrieren? Minimierung zukünftiger Aufwand (den man eh vergisst) unso ;)

**Comment by sascha11110** [comment]
Habe ich auch schon überlegt. Muss ich mir anschauen.

Martin Schrimpf <notifications@github.com> schrieb am So., 17. Jan. 2016 um
23:12 Uhr:

**Comment by sascha11110** [comment]
Habe folgendes gemacht:
Über den Netzwerk Admin kann jetzt mit einem WYSIWYG Editor ein neuer Tab in die Hilfe eingefügt werden. Da kann dann das Video oder auch ein Link zum Handbuch rein.

Der Klickguide fügt auch einen Tab hinzu, über den er aufgerufen werden kann.

Ist das Plugin für den Klickguide oder der benutzerdefinierte Tab aktiv, wird die Hilfe auf allen Seiten angezeigt.

**Comment by Meash** [comment]
Nice klingt gut!

**Comment by sascha11110** [comment]
Solved by #280.
