### ISSUE TITLE
Beim Erstellen einer neuen Seite direkt die Anordnung innerhalb der Baumstruktur anbieten

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#147]

**Comment by dkehne** [comment]
Wird doch gemacht. Zumindest wenn man aus der Baumstruktur direkt erstellt. Ich seh hier kein Issue....

**Comment by Meash** [comment]
Nicht, wenn man in der Baumstruktur auf den `Erstellen` Button drückt. Dann muss man erst Inhalt eintragen und muss wieder zurück in die Baumstruktur, um die neue Seite einzuordnen.
Cool wäre hier zb die Möglichkeit, zwischen zwei Seiten zu hovern, womit die Möglichkeit zum Erstellen an dieser Stelle geboten wird - ist aber vermutlich nicht intuitiv für unsere Nutzer.
Sonstige Ideen?

**Comment by dkehne** [comment]
Ja verstehe ich. Ich finde das Hovern ist aber Best Practise und werden wir auch in den Schulungen so an die Leute weitergeben. Das merkt man spätestens dann wenn man 3-4 Seiten mal selbst erstellt hat, dass das viel einfacher geht. Von daher würde ich die FUnktionalität hinter dem "Erstellen" Button gar nicht antasten
