### ISSUE TITLE
Übersetzungsmanagement

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#148]
- Pool mit allen Inhalten (alle Städte) und Suchfunktion
- Kombination von globalen und lokalen Inhalten ermöglichen
- Änderung von globalen Inhalten durch einsetzen in benutzerdefinierte Felder (z.B. Adressen)
- Getaggte Übersetzung-Schnipsel (z.B.: „Morgen ist eine Veranstaltung…“) mit Suchfunktion

**Comment by Meash** [comment]
Erstmal keine Textschnipsel.
Für Übersetzungsmanagement nutzen wir WPML Translation Management.
