### ISSUE TITLE
Sub-Sites (Kommunen) in Admin-Ansicht freischalten

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#154]
Wird derzeit in plugin `wp-api-extensions/endpoints/RestAPI_Multisites.php` per IDs gelöst.
Die muss man zum Freischalten also jedes mal im Code ändern und pushen.

Zwei Vorschläge:

1. man kann die Seiten in den Netzwerk-weiten Einstellungen an- und abhaken (live or not)
2. man kann die Seite in ihren eigenen Einstellungen auf live oder nicht live schalten

**Comment by dkehne** [comment]
Der zweiten Kommentar von dir existiert noch als Issue und finde ich sinnvoll. Was ist mit dem ersten Teil - ist der bereits abgeschlossen oder noch relevant?

**Comment by Meash** [comment]
Ist noch zu erledigen. Derzeit muss man jedes mal die Datei https://github.com/Integreat/cms/blob/4df8f9d763a8c49527c3ca75efe4cd76f5ccc36b/wp-content/plugins/wp-api-extensions/endpoints/liveinstances.txt anfassen.

**Comment by sven15** [comment]
AFAIK solved with the "Live" checkbox.
