### ISSUE TITLE
Location-Images verbessern

### ISSUE THREAD

**Issue by Dalanie** [Integreat/cms#156]
Die aktuellen Images (Augsburg, Main-Taunus-Kreis) sind nicht sehr schön darstellbar in Android.

Zum einen ist der Hintergrund nicht transparent, zum anderen ist das Augsburg Logo klein, da sehr breit und der Text ist jetzt doppelt dargestellt.

Mir ist klar, dass jede Stadt entsprechende Anforderungen an Ihr Logo hat, aber geht da nicht vielleicht etwas anders?

Wie wäre es mit nem Google-Maps Kartenausschnitt oder irgendwas andrem?

Wir werden wohl in Android Google-Maps einbinden können, aber ich würde trotzdem gerne die alte Darstellung als "Fallback" haben - falls kein maps installiert ist oder das netzwerk zu schlecht.

**Comment by Meash** [comment]
Inzwischen werden Cover Images angezeigt.
