### ISSUE TITLE
PDF-Creator kann arabische Zeichen nicht

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#158]
Der PDF-Creator kann keine arabischen Zeichen drucken. Stattdessen nur "Fragezeichen", da der Font fehlt(?).

**Comment by pblanz** [comment]
Also ich habs jetzt hinbekommen mit den pdf-creator-lite code zu modifizieren so dass das PDF richtig erzeugt wird.

![example](https://cloud.githubusercontent.com/assets/14991786/11143730/a6ef790a-89f7-11e5-91a3-bfc1378d84f4.PNG)

 Dafür muss ein anderer Font ausgewählt werden.

![example2](https://cloud.githubusercontent.com/assets/14991786/11143733/ad7a4fd4-89f7-11e5-8d00-b4c1c55803d4.PNG)

Wenn man die Font-Selektoren entsprechend betitelt etwa "persian-font" für persisch und "arabian-font" für arabisch sollte das ja passen, oder?

Ich habe das ganze jetzt nur mit persisch ausprobiert. Vllt funtioniert der aerufat font ja auch für beides. Gibt's auch schon irgendwo arabisch Übersetzungen?

Da wir uns wie @Meash schon richtig bemerkt hat darauf geeinigt hatten nicht den plugin source code zu modifzieren versuch ich mal ein kleines Plugin dafür zu schreiben.
Man könnte sich überlegen ob dieses noch die zusatzfunktionalität  bieten sollte, weitere fonts (.ttf files einzubinden über eine entsprechende admin-oberfläche einzubinden.)

**Comment by systemiya** [comment]
Was ist mit RTL? Das wird da jetzt allerdings nicht berücksichtigt

**Comment by pblanz** [comment]
Ok, es gibt Sprachen die von links nach rechts gelesen/geschrieben werden und Sprachen bei denen es eben anders herum läuft. Das kann man ja für die entsprechenden Sprachen einstellen (<code>$pdf->setRTL(<b>true</b>);</code> oder halt <code>$pdf->setRTL(<b>false</b>);</code>). Oder haben wir viele Mix-Dokumente mit verschiedenen Sprachen? In der Regel werden die Seiten ja vollständig übersetzt, oder?

**Comment by systemiya** [comment]
Ich mein nur, weil in dem Dokument das du gepostet hast, ist es eben RTL (siehe Ausrufezeichen und Punkte auf der linken Seite)

**Comment by pblanz** [comment]
Stimmt und nach kurzem recherchieren wird <code>setRTL</code> auch von der app nirgendwo verwendet. Aber das müsste man ja über hooks irgendwie reinbasteln können.

**Comment by Meash** [comment]
Schaut gut aus, geplanten Plug-in Ansatz finde ich gut.
Die Sprache bzw. Font würde ich abhängig von der aktuellen Sprache
einstellen (`ICL_LANGUAGE_CODE`).

Android zeigt RTL abhängig vom Text ab, passiert dort also automatisch.

**Comment by pblanz** [comment]
Android ja, aber wie wird denn das PDF plugin überhaupt verwendet? Wird das nicht von Lokalverantwortlichen die das Wordpress CMS verwalten (sprich am PC)?

**Comment by Meash** [comment]
Ja richtig. 
Sorry, habe mich verlesen mit android.

**Comment by pblanz** [comment]
also, das mit dem erweitern der Funktionalität des pdf-creator-lite plugins über ein eigenes Plugin gestaltet sich schwierig, da der Plugin Autor keine action hooks in seinen source-code eingebaut hat. Daher schlage ich vor, das wir den source-code des Plugins verändern (das wird auch explizit von den Autoren gewünscht (s. deren Kommentare im source-code)). Es wären auch keine großen Änderungen. Vllt. kann man die Änderungen auch dokumentieren und das Änderungsfile mit in den Plugin-Ordner schmeißen?
Sonstige Vorschläge?

**Comment by pblanz** [comment]
Ein Mittelweg wäre custom hooks in den plugin source-code einzufügen die ich dann in einem eigenen Plugin verwenden könnte.

**Comment by Meash** [comment]
Wir könnten auch von deren Source-Code forken, wird aber auch bissl aufwändig.
Kann man irgendwie die Verknüpfung mit dem ursprünglichen Plugin brechen, sodass keine Updates mehr vorgeschlagen werden?

**Comment by pblanz** [comment]
Ja, es ist möglich die update Notifications zu <a href="http://wpguru.co.uk/2013/09/how-to-disable-update-notifications-in-wordpress/">deaktivieren</a>.
Gibt es auch Möglichkeiten ein plugin zu erweitern, wenn dieses keine hooks anbietet und ohne das man den plugin source-code verändert?

**Comment by Meash** [comment]
Es gibt noch diese [Filter](https://codex.wordpress.org/Function_Reference/add_filter), hab ich mir aber noch nicht genauer angeschaut.

**Comment by pblanz** [comment]
ja, die haben 2 filter hooks in ihrem source code, mit denen kann man aber nicht wirklich was anfangen...

**Comment by Meash** [comment]
Dann würde ich entweder das repository von denen forken oder die Updates ausschalten.

**Comment by pblanz** [comment]
Also hab das pdf-creator-lite-font-extension plugin auf den gleichnamigen branch gepusht. So auch die modifizierten php skripte des pdf-creator-lite plugins. Ich habe mich bemüht die Änderungen so klein wie möglich zu halten. Insgesamt habe ich zwei zeilen code hinzugefügt. Für Details, siehe README-file im pdf-creator-lite-font-extension plugin. Dort steht auch ein Hinweis zur Installation von neuen Fonts. Habe jetzt mal zwei fonts vorinstalliert, welche für arabische/persische zeichen verwendet werden können. RTL wurde für die beiden fonts auf true gesetzt. Allerdings werden dann alle Inhalte (auch lateinische Zeichen) von Rechts nach Links geschrieben.

Zudem habe ich noch ein weiteres Plugin in den Branch gepusht. Namentlich block-specific-plugin-updates, welches (wie der Name schon beschreibt) Updates von ausgewählten Plugins blockt.

**Comment by pblanz** [comment]
Man könnte sich noch überlegen ob man die PDF-files branden möchte, sprich in die Kopfzeile das Integreat-Logo o.ä. setzen.

**Comment by Meash** [comment]
Guter Gedanke, würde ich in ein separates Issue packen.

**Comment by Meash** [comment]
@pblanz Machst noch einen Pull Request für den Branch? In der rechten Sidebar unter Issues ist die Pull Requests Übersicht, gibt bestimmt auch eine Anleitung im Web.

**Comment by pblanz** [comment]
Sorry, hatte ich vergessen. Sollte jetzt ausgeführt sein. Soll ich Änderungen (wie etwa das "branden" der PDFs) an dem plugin wieder auf nen  branch pushen oder gleich auf master?

**Comment by Meash** [comment]
Ich mach selber immer einen neuen branch, der vom aktuellen develop branch
geforked ist. Ansonsten sind in der commit history beim pull request die
ganzen commits drin, die man noch rein mergen musste.

**Comment by Meash** [comment]
solved in 28d44c8
