### ISSUE TITLE
Name der Instanz ändern als Verwaltung 

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#160]
Als Admin kann man den Titel der Seite unter Einstellungen > allgemein ändern. 
Ein Verwalter sieht die Einstellungen nicht, sollte den Titel aber auch ändern können. (sonst nichts!)

Evtl muss man hier ein bisschen mit den Berechtigungen rum spielen, da WordPress AFAIK alle Einstellungen unter `manage_options` zusammen fasst.

**Comment by benginoe** [comment]
Soll sich hierdurch die Webadresse/Subdomain ändern?

**Comment by dkehne** [comment]
Das Recht würde ich ihm nicht geben. Geburtshelfer-Mentalität schön und gut, aber dafür sollen die uns anpingen! :)
