### ISSUE TITLE
PDF-Creator funktion ohne Login auf Frontend möglich

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#163]
Mega wichtig für den Release am 26.11! Können wir das umsetzen? Sprachenauswahl und das an- und abwählen von Kapiteln sollte möglich sein.

**Comment by Meash** [comment]
Sprachauswahl ist implizit gegeben durch den Sprahumschalter.
Reicht der Download der derzeitigen Seite? 
Folgende Einstellmöglichkeiten gibt es out-of-the-box:
![delete](https://cloud.githubusercontent.com/assets/5308236/11166040/f42defa8-8b23-11e5-9074-edec918dff3d.PNG)

**Comment by dkehne** [comment]
Falls ich auch mehrere Seiten auf einmal downloaden kann und der Weg der Navigation zu einer Seite (z.B. durch ein gutes Domain-Konzept) gegeben ist, ja.

**Comment by sven15** [comment]
Naja, so wie ich das hier interpretiere, ist keine manuelle Wahl möglich. Entweder geben wir den Parameter allpages="true" oder wir müssen über titlepage alle Seiten einbinden, die wir wollen. Wir könnten höchstens Buttons zu verschiedenen Kapiteln machen. Die müssten aber manuell gepflegt werden. Außerdem brauchen wir eine Seite, die auf der Website erscheint, aber nicht in der App.

**Comment by dkehne** [comment]
Kann man das noch oben auf die Webview mitdraufnehmen? Input @Meash wie realisitisch ist die Umsetzung?

**Comment by Meash** [comment]
Ja, so wie Sven gesagt hat: das in jede Seite einzubauen + allpages in der Übersicht geht relativ straight-forward.

**Comment by sven15** [comment]
Wenn eine Überschriftsseite kommt, automatisch alle Unterseiten vorselektieren. Häkchen umsetzbar. Sprache auswählbar.

**Comment by FritjofK** [comment]
Schafft das jemand bis zur nächsten Konferenz?

**Comment by FritjofK** [comment]
Selbe Frage noch mal. Auch weil die Hits über die Web-App sehr vielversprechend aussehen. Wäre für die Beratung ganz wichtig.

**Comment by sven15** [comment]
@dwsoto @ammyg @pblanz could one of you take on this issue?

**Comment by sven15** [comment]
Nev0r mind, taking over. It's I7K!!!!!!
