### ISSUE TITLE
Übersicht Fortschritt Instanz

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#164]
Kommentar von @mwi-tum: für die Aquise (und insb followup) wäre es total cool, einen view auf den Stand der erstellen Texte zu haben. Ich stelle mir da so eine Kombination aus burndown chart und heat-map vor

**Comment by dkehne** [comment]
Das Issue würde ich liebend gerne closen. @Meash ? Darf ich? Machst du?

**Comment by Meash** [comment]
Jo. Analytics sind cool, noch wissen wir aber nicht, was genau wir eigentlich wollen. Würde da erstmal mit den benutzten Sprachen/Seiten anfangen (Integreat/app-cross_platform#15)
