### ISSUE TITLE
Open source formalities

### ISSUE THREAD

**Issue by MaximilianSchreieck** [Integreat/cms#171]
- choose license
- create license file
- create notice file
- create header for all code files
- reference libraries and their licenses (needs to be checked depending on the licence of the integrated component)

(see here example for Apache 2.0: http://www.apache.org/dev/apply-license.html#new
"To apply the ALv2 to a new software distribution, include one copy of the license text by copying the file:

http://www.apache.org/licenses/LICENSE-2.0.txt

into a file called LICENSE in the top directory of your distribution. If the distribution is a jar or tar file, try to add the LICENSE file first in order to place it at the top of the archive. This covers the collective licensing for the distribution.

In addition, a correct NOTICE file MUST be included in the same directory as the LICENSE file.

Each original source document (code and documentation, but excluding the LICENSE and NOTICE files) SHOULD include a short license header at the top. If the distribution contains documents not covered by CLA, CCLA or Software Grant (such as third-party libraries) then see the policy guide.")

**Comment by Dalanie** [comment]
wir sollten die Apache Licence wohl auch in die Android-App hinzufuegen

**Comment by MaximilianSchreieck** [comment]
Auf jeden Fall auch in der App, wenn die Lizenz-Entscheidung gefällt ist. Die genutzten Komponenten und ihre Lizenzen müssen dann evtl. auch referenziert werden, je nach Lizenz

**Comment by MaximilianSchreieck** [comment]
@sven15 Kannst Du die gewählte Lizenz für die Software hier nochmal angeben und im besten Fall gleich License-File bereitstellen? Was muss aus Deiner Sicht noch beachtet werden?

**Comment by Meash** [comment]
Ich close hier, License Files sind in den Repos.
