### ISSUE TITLE
Anordnung des Seiten-Trees weicht bei den Sprachen ab. 

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#172]
Wenn ich z.B. im Augsburg CMS auf die Englische Seitenübersicht umschalte, liegt dort auch eine andere Anordnung der Seiten vor.

In der deutschen Augsburg-Version ist "Willkommen in Augsburg" ganz oben. In der englischen Version "Meeting places and social cafés". In der App wird alles richtig (á la deutsche Version) angezeigt.

Ist das gewollt oder kann man das fixxen?

**Comment by dkehne** [comment]
Das müssen wir in den Griff bekommen. Baustelle Tree View. @dwsoto  - kannst du das gemeinsam mit dem Problem beim Verschieben und den Übersetzungssachen übernehmen?

**Comment by sven15** [comment]
I think this was fixed with  #recursive-autotranslation
