### ISSUE TITLE
Analytics in CMS seitenspezifisch anzeigen

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#173]
Ist es möglich Analytics (z.B: Anzahl Nutzer, welche Sprachen) pro CMS einzubinden, sodass die Nutzerrolle "Verwalter" darauf einen Blick hat?

Gruß,
Daniel

**Comment by sascha11110** [comment]
Gibt m.E. mit vorhandenen Plugins nur die Möglichkeit, die Daten zusammen
zu erfassen oder man muss für jede Instanz einen extra Tracking Code
einbauen. Das man nur die Infos für die Instanz bekommt, muss man also
selber programmieren. Sollte aber nicht so aufwendig sein. Gibt eine API
für Google Analytics.

Bei der Nutzung von Google Analytics muss man auf jeden Fall einen extra
Punkt Datenschutz (reicht nicht im Impressum) anlegen und darauf hinweisen,
dass Google Analytics genutzt wird. In der Web Ansicht muss auch ein Opt
out Cookie angeboten werden..



Daniel Kehne <notifications@github.com> schrieb am So., 15. Nov. 2015 um
10:40 Uhr:

**Comment by dkehne** [comment]
Kommt mit Xamarin!

**Comment by sven15** [comment]
Is there a difference to #342?

**Comment by Meash** [comment]
Nope.

**Comment by sven15** [comment]
We be a nice to have for the Integreat Forum in late summer 2017.

**Comment by sven15** [comment]
It should be possible to write a simple hit counter for the web frontend and API requests and display this in the backend.

**Comment by svenseeberg** [comment]
The new web app makes tracking right now impossible ... everything shows up as app refreshes.
