### ISSUE TITLE
Titelbild und Farbe bei Location mitliefern

### ISSUE THREAD

**Issue by Dalanie** [Integreat/cms#178]
Jede Location sollte ein Titelbild und eine Farbe mitliefern - Ist das nicht irgendwie einstellbar?
Farbe ist von mir aus erstmal unwichtig... aber hardgecoded nen Titelbild einzubinden ist nicht sehr schön :(

**Comment by Meash** [comment]
Wir könnten's erstmal serverseitig hardcoden, müssen die Funktionalität in WordPress erst einbauen.

**Comment by Meash** [comment]
In welcher Größe sollen die Titelbilder sein?

**Comment by Meash** [comment]
Beispielhafte neue Rückgabe:

    [{
        "id":"2",
        "name":"Augsburg",
        "icon":"http:\/\/localhost\/wordpress\/wp-content\/uploads\/sites\/2\/2015\/09\/cropped-augsburg.png",
        "cover_image":"http:\/\/localhost\/wordpress\/augsburg\/wp-content\/uploads\/sites\/2\/2015\/11\/cropped-1280px-Augsburg_-_Markt.jpg",
        "path":"\/wordpress\/augsburg\/",
        "description":"Augsburg",
        "global":false
    },{
        "id":"8",
        "name":"D\u00fcsseldorf",
        "icon":"http:\/\/localhost\/wordpress\/wp-content\/uploads\/sites\/8\/2015\/10\/cropped-duesseldorf-logo.png",
        "cover_image":"",
        "path":"\/wordpress\/duesseldorf\/",
        "description":"D\u00fcsseldorf",
        "global":false
    }]

**Comment by Dalanie** [comment]
merci! kannst du vllt auch ne farbe mitgeben? die koennen wir ja erstmal manuell setzen ;)

**Comment by Meash** [comment]
Yellow oder was sollte das sein? 
Welche size des covers?

**Comment by Dalanie** [comment]
Irgendwas halt pro Stadt.

**Comment by Meash** [comment]
Laut https://github.com/google/iosched/blob/master/android/src/main/res/drawable-nodpi/default_cover.jpg 600:450.5

**Comment by Dalanie** [comment]
Abweichungen bis 10% können ruhig erlaubt sein von der Skalierung, sollte
kaum sichtbare Unterschiede machen
