### ISSUE TITLE
Falsches Modification date bei geplanten Inhalten

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#179]
@ammyg hat in Integreat/app#95 festgestellt, dass post_modified_GMT der Zeitpunkt des speichern, nicht des veröffentlichen ist. Dadurch kann es zu Problemen beim abrufen seitens der App kommen.
-> ändern auf post_date_GMT und nochmal prüfen, dass das auch wirklich die Veröffentlichung ist.

**Comment by Meash** [comment]
Scheint doch nicht so einfach zu sein, post_date wird nur bei der Veröffentlichung gesetzt und dann nicht mehr aktualisiert.

**Comment by ammyg** [comment]
Bei WordPress bin ich keine große Hilfe. Ich habe damit noch nie wirklich gearbeitet.
Ich habe das selbst auch nur für geplante Inhalte getestet und dann angenommen, dass das auch bei Freigabe zu dem Fehler kommt.

Nutzen wir geplante Inhalte? Bzw. haben wir die genutzt, als der Fehler bei @Dalanie aufgetreten ist? Nur um sicher zu gehen, dass wir nicht doch einen weiteren Fehler in der App haben.

**Comment by Dalanie** [comment]
Da kann ich leider nichts zu sagen, der Fehler kam von außen und wir haben nur eine E-Mail-Bug-Beschreibug.

**Comment by dkehne** [comment]
@ammyg gibts hier schon was neues? Ist das immernoch so?

**Comment by sven15** [comment]
Can someone confirm that this is still an issue?
