### ISSUE TITLE
PDF Export - Sprachen der Überschriften

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#186]
Beim PDF-Export wird bei der Seiten-Auswahl immer nur die aktuell gewählte Sprache angezeigt. Wer kein Arabisch kann und die Seitenstruktur nicht auswendig kennt, kann nicht sinnvoll arabische Inhalte exportieren. Dh es sollten immer die deutschen oder englischen Überschriften neben den arabischen / persischen / etc angezeigt werden.

**Comment by pblanz** [comment]
Ich hab jetzt mal die deutsche und englische Übersetzung hinten dran gesetzt (s. Bild). Positiver Nebeneffekt. Man sieht sofort in welchen Sprachen bereits eine Übersetzung existiert (noch nicht getestet). Ich könnte das theoretisch noch schöner formatieren und für alle Sprachen in einer Tabelle darstellen. Dann hätte man direkt eine Übersicht. Ich glaube das hatten wir auch schon mal diskutiert, oder @Meash .

![languages](https://cloud.githubusercontent.com/assets/14991786/11812414/1289ee4a-a33c-11e5-87e4-a61ce2f01ca3.PNG)

**Comment by Meash** [comment]
Ich find's super so, würde es erstmal dabei belassen.

**Comment by pblanz** [comment]
resolved in 10b34dc127ba9a3775c16172aecbb4cf92515585
