### ISSUE TITLE
Farsi Icon

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#187]
Laut Feedback ist der Farsi Icon ähnlich kritisch/out-dated wie Arabisch es mal war @julia-goetz

**Comment by julia-goetz** [comment]
![ea13ed76-8879-11e5-93ca-f53a02ed1d0c](https://cloud.githubusercontent.com/assets/14897768/11287201/44c3ceb6-8f1a-11e5-87c2-e37c3765f1a2.png)

**Comment by Meash** [comment]
Muss noch in die WPML resources übernommen werden
