### ISSUE TITLE
Flaggen Arabic/Farsi/...

### ISSUE THREAD

**Issue by julia-goetz** [Integreat/cms#188]
Hübschere Optik als alle Grau @julia-goetz

**Comment by Meash** [comment]
Schon was Neues?

**Comment by julia-goetz** [comment]
Würde vll. Sinn machen, das den Desginern mitzugeben, vor ich da rumpfusche - dann passt es ins UI. Oder? Ansonsten überleg ich mir am Sa was

**Comment by Meash** [comment]
Good point, vlt haben die auch Erfahrungswerte.

**Comment by dkehne** [comment]
Fritjof - kannst du das übernehmen?

**Comment by sven15** [comment]
I think this is done.
