### ISSUE TITLE
Verwalterrolle kann keine Medien/Bilder löschen

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#189]
Auf der Landing Page kann ich Mediendateien löschen in der Augsburg Instanz z.B. nicht. Button "unwiderruflich löschen" fehlt.

**Comment by dkehne** [comment]
Gibts hier schon was neues @sven15 - kannst du das anpassen?

**Comment by sven15** [comment]
Das hat sich erleidgt. Landing page ist weg und das Issue ist weitergezogen zu #331
