### ISSUE TITLE
Gesondertes Impressum 

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#192]
Impressum statt über die Seiten in einem gesonderten Menüpunkt bereitstellen, sodass es in der App gesondert angezeigt werden kann. 
Integreat/app#117

Sollte mehrsprachig und änderbar sein.
Umsetzungsvorschlag: neues Plug-in, das einen neuen Post_type definiert und von unseren API extensions erbt, um geänderten content auszuliefern.

**Comment by Dalanie** [comment]
Wenn ihr es für nötig haltet ja, ansonsten hardcoded. Man kann neue
Versionen ja immer noch durch Android Updates ausrollen, wenn wir später
jedoch mehrere Versionen(ios, winphone,..) haben ist es komplizierter

**Comment by Meash** [comment]
Läuft prinzipiell, aber derzeit wird die WPML Configuration erst angepasst, nachdem man in die Übersetzungsoptionen geht. Support Ticket ist offen: https://wpml.org/forums/topic/configuration-only-activated-after-going-into-translation-options/

**Comment by Meash** [comment]
@dkehne Es gibt in Augsburg jetzt für den Verwalter ein Impressum in der linken Sidebar, bitte übernimm die Sachen, die nicht in der normalen Seitenstruktur angezeigt werden sollen, dort rein.

**Comment by dkehne** [comment]
Ja, geht aktuell aber nur auf deutsch?

**Comment by Meash** [comment]
Siehe 2 Kommentare über deinem....

**Comment by dkehne** [comment]
Wer lesen kann ist klar im Vort...alles klar!

**Comment by Meash** [comment]
Antwort WPML Support:

> No, there is no option to change the pages above.
> Like I said above, you need to write some custom code to force this.
> This scanning is written at: `sitepress-multilingual-cms\inc\wpml-config\wpml-config.class.php`
> The method load_config_run() is static, and you can run it like this:
> `WPML_Config::load_config_run();`
> However, please check the conditions carefully to run this; if not, you may get unexpected errors.
> Since this is a kind of custom code, we don't support to debug it.

**Comment by dkehne** [comment]
Scheint jetzt zu laufen!

**Comment by Meash** [comment]
Nein. Die Aktivierung für jede Multisite ist noch nicht implementiert (s.o.).

**Comment by dkehne** [comment]
Wie machen wir hier weiter?

**Comment by Meash** [comment]
Die Aktivierung für jede Multisite implementieren ;-)
WPML Support hat uns ja schon den hint zu `WPML_Config::load_config_run();` gegeben, das allein klappt nur leider nicht.

**Comment by dkehne** [comment]
Funktioniert doch jetzt oder ?

**Comment by Meash** [comment]
Nein, die multisite Aktivierung ist immer noch nicht korrekt implementiert... Ist nur für Augsburg aktiv.

**Comment by sven15** [comment]
Impressum wird nur einsprachig gebraucht. Juristisch verbindlichen Text will sowieso keine Stadt übersetzen.
