### ISSUE TITLE
PDF Creator: Fontauswahl unnötig

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#193]
Standardmäßig sollte die Font ausgewählt sein, die für alle Sprachen funktioniert (@pblanz welche war das nochmal?).

**Comment by pblanz** [comment]
Hab jetzt zwei Standard fonts hinzugefügt. "aefurat" und "dejavusans".  Aefurat funktioniert mit arabisch und dejavusans mit Persisch. Werden jetzt automatisch ausgewählt, je nachdem welche Sprache gerade benutzt wird.

Hab den Code wieder in den pdf-creator-light-font-extension path gepusht.

Kommen noch andere Sprachen mit exotischen Zeichen dazu? Ansonsten muss ich die automatisch Sprachauswahl auch im Code ergänzen?

**Comment by pblanz** [comment]
@Meash: Achja, dejavusans funktioniert nicht für alle fonts (wie ich naiverweise dachte).

**Comment by Meash** [comment]
Okay dann dejavusans für ICL_LANGUAGE_CODE == 'ar' oder 'fa'?

**Comment by pblanz** [comment]
Ehm, dejavusans für Persisch, also 'fa' . So hab ichs bereits implementiert.

**Comment by Meash** [comment]
Für arabisch 'ar' sollten wir's auch anschalten oder? Da kommen sonst nur Fragezeichen glaub ich.

**Comment by pblanz** [comment]
ja, ist beides bereits in "Version1.1" des plugins drin. Funktioniert's bei dir noch nicht?

			if(strcasecmp($filename, 'dejavusans') == 0){
				if(strcasecmp(ICL_LANGUAGE_CODE, 'fa') == 0){
					$first = '<option value="'.$filename.'" selected>'.$filename.'</option>';
				}
				else{
					$selection.= '<option value="'.$filename.'">'.$filename.'</option>';
				}
			}
			//for arabic we use aefurat
			else if(strcasecmp($filename, 'aefurat') == 0){
				if(strcasecmp(ICL_LANGUAGE_CODE, 'ar') == 0){
					$first = '<option value="'.$filename.'" selected>'.$filename.'</option>';
				}
				else{
					$selection.= '<option value="'.$filename.'">'.$filename.'</option>';
				}
			}

**Comment by pblanz** [comment]
Hmm, ich seh grad, da läuft noch immer was schief... Bei mir lokal läuft alles... Ich schau mal worans liegt

**Comment by pblanz** [comment]
Also ich dachte ich hätte auch Änderungen in den Klassen "build-pdf-admin.php" und "adminpage.php" commited und in den branch gepusht. Die sind aber noch nicht auf dem Testserver. Ich schreib heute noch Version 1.2 fertig und commite wieder in den Branch. Kannst du das dann morgen gleich auf den Testserver schieben?

**Comment by Meash** [comment]
Ja wenn du die Änderungen in deinem feature branch gepushed hast, mach einfach einen pull request und ich merge sie in den develop und dann den master branch.

**Comment by pblanz** [comment]
ja mach ich!

**Comment by Meash** [comment]
resolved in #213
