### ISSUE TITLE
Ids - Location/Language/Page/Event - unique?

### ISSUE THREAD

**Issue by Dalanie** [Integreat/cms#200]
Welche Ids sind nochmal unique? Benötige ich zusätzlich zur Id von Location/Language/Page/Event ein anderes Attribut um unique zu sein?

Muss ich für den Xamarin-Port wissen, in Android habe ich einfach alles was irgendwie in den Key passt, reingesteckt. ;)

**Comment by Meash** [comment]
Page, Location, Event are unique per instance.
User, Language are globally unique.
