### ISSUE TITLE
Blogeintrag (Beitrag) wird automatisch übersetzt

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#202]
Aktuell wird, selbst wenn ich den Haken bei "Einrichtung des mehrsprachigen Inhalts" rausnehme, der Inhalt auch auf arabisch und englisch angelegt. Das ist blöd, weil er dann auf den Social Media Plattformen jeweils 3 Postings macht mit AutoTranslation in Englisch und Arabisch.

Können wir das für Beiträge deaktivieren?

**Comment by Meash** [comment]
Ich finde, wir sollten die Landing Page eh langsam in eine eigene WordPress Instanz umziehen. 
Die Plugins überschneiden sich kaum mit den eigentlichen Instanzen.

**Comment by sascha11110** [comment]
Bin ich auch für, zumal ich bei Überarbeitung der Seite noch einen Haufen
Plugins installieren werde, die für die anderen Instanzen nicht gebraucht
werden

Martin Schrimpf <notifications@github.com> schrieb am Di., 24. Nov. 2015 um
09:06 Uhr:
