### ISSUE TITLE
Uploads aus .gitignore entfernen

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#205]
Auf dem Server werden alle Uploads beim `git status` gelistet, die für die Versionsverwaltung nicht interessieren.

Schlage vor, wir nehmen `wp-content/uploads/` in die .gitignore auf.

**Comment by dkehne** [comment]
Quick-Win, Quick-Win. Yeah yeah.  @Meash kannst du kurz aktiv werden und dann gebe ich in diesem Ticklet für immer Ruhe.
