### ISSUE TITLE
Plugin Updates nur auf Instanz-Ebene blockbar

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#206]
In #158 und 28d44c8 wurde das Plugin "Block Plugin Updates" eingeführt, um die Updates für spezifische Plugins auszuschalten.
Leider geht das bislang nur in den Instanz-weiten Einstellungen (Augsburg, Düsseldorf etc.), nicht aber auf der Netzwerkebene. Kann man die Updates irgendwie netzwerkweit verhindern?

**Comment by pblanz** [comment]
Das Plugin sieht nicht besonders kompliziert aus. Ich erstelle daher ein eigenes Plugin, welches ermöglicht, Plugins aus Instanz-Ebene und global zu blockieren. Als Settingsmenü schlage ich eine Tabelle mit Check-Boxen vor:

|                | Global    | Instanz A | Instanz B | ... |
| -------------- |:-------------:| :------------:|:--------------:|:----|
|Plugin A    | -            |O             |O             | ... |
|Plugin B    | X            |X             |X              | ... |
|Plugin C    | -            |O             |O             | ... |
|Plugin D    | -            |X             |O              | ... |
|...             | -            |O             |O             | ... |

Das Menü ist dann nur global zu erreichen.

**Comment by Meash** [comment]
Soweit ich mich erinnere, geht es bei diesem Issue nur um die Updates von Plugins.
@Integreat/orga brauchen wir auch zentrale Einstellungen für die Aktivierung/Verwendbarkeit von Plugins?

**Comment by sven15** [comment]
Can this be solved by configuring it in the master instance? The settings are probably kept while copying it for a new city / region.

**Comment by mschrimpf** [comment]
Yeah that's probably sufficient for our case.

**Comment by sven15** [comment]
Configured it for "Deutschland". We have to do it manually for all instances ;-/

**Comment by sven15** [comment]
@FritjofK @janiner256 Something for you: deactivate automatic updates in all cities.

**Comment by sven15** [comment]
We need a plugin that on activation automatically sets all disable plugin update flags on all blogs for all plugins.

**Comment by sven15** [comment]
All Updates are disable via core setting in commit 914d23a704225d7dfdd616651475ea843206b2ef
