### ISSUE TITLE
Default - Gelb bei Locations zu "grell"

### ISSUE THREAD

**Issue by Dalanie** [Integreat/cms#219]
Die momentane Farbwahl für die Anwendung stört dem Auge sehr - bitte ein dunkleres Gelb nehmen ;)
https://www.materialpalette.com/ schaut mal hier

**Comment by Meash** [comment]
Schick einfach einen Hexcode nahe am Integreat Gelb, der auf der App gut aussieht. Gerne das bisherige Gelb in bissl dunkler o.ä.

**Comment by Dalanie** [comment]
#FFC107 wäre am nahsten dran. Ich bin persönlich für ne dunklere Variante #FFA000
