### ISSUE TITLE
Location-Bild immer mitliefern oder Default-Bild einstellen

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/cms#222]
Ich finde das bisherige Default-Bild (Brandenburger Tor) ungünstig. Das wird jetzt gerade angezeigt, da Bad Tölz kein Bild hat.

Könnt ihr IMMER ein Bild mitliefern?

Wenn nicht: Was kann ich als default-verwenden?

**Comment by sven15** [comment]
Wie wäre es notfalls mit dem Icon aus der Stadtauswahl?

**Comment by Dalanie** [comment]
Seit der neuesten Version gibt es nur noch das Icon der Stadtauswahl - Wappen werden nicht mehr angezeigt

**Comment by sven15** [comment]
Also für Bad Tölz versuche ich seit gestern ein Bild zu bekommen. Aber als Fallback finde ich das Brandenburger Tor gar nicht so schlecht. Es ist immerhin eindeutig 'Schland.

**Comment by Dalanie** [comment]
Schon, aber wenn wir ne Deutschlandinstanz haben ist es mehrdeutig

**Comment by Meash** [comment]
Deutschland Instanz ist derzeit ziemlich aus dem Rennen (wir sind lokal), würde es auch beim Brandenburger Tor belassen for now.

**Comment by dkehne** [comment]
Ja würde ich auch. Ich füge für die aktuellen BETA Städte überall mal ein adäquates Logo ein.

**Comment by dkehne** [comment]
Ich habe alle ergänzt auf die ich Zugriff hatte ohne mir einen User erstellen zu müssen. Soll ich mir bei den restlichen noch einen erstellen oder übernimmst du Martin? Habe nach Möglichkeit die Wikipedia-Bilder genommen und vor Veröffentlichung müssen wir da unbedingt mit der Stadt drüber sprechen.

**Comment by Meash** [comment]
Du bist super-admin, kommst also überall rein (Netzwerk Verwaltung >
Websites).
Danach kannst closen, default Bilder haben wir implizit, indem wir immer
die Instanzen `Deutschland` bzw `empty base instance` duplizieren. Dort
könnte man als default Bild auch das Integreat Logo nehmen.

**Comment by sven15** [comment]
We need the default image but for live instances "real" images are usually delivered.
