### ISSUE TITLE
Feedback requested - Webpage Design Sketches 

### ISSUE THREAD

**Issue by elordin** [Integreat/cms#225]
Verschiedene Varianten für das Design der WebView
(Höhere Auflösung im Drive)

![small_sketches_website_01](https://cloud.githubusercontent.com/assets/6238752/11411269/dae75d1e-93ce-11e5-95b1-056f4b7ccecd.png)
![small_sketches_website_02](https://cloud.githubusercontent.com/assets/6238752/11412009/76ca6c96-93d7-11e5-9371-3b8449e7f5a8.png)
![small_sketches_website_04](https://cloud.githubusercontent.com/assets/6238752/11411258/ca6409a6-93ce-11e5-96c5-a64aba79c270.png)
![small_sketches_website_05](https://cloud.githubusercontent.com/assets/6238752/11411260/ca7c5632-93ce-11e5-8053-74471d2b0e1e.png)
![small_sketches_website_06](https://cloud.githubusercontent.com/assets/6238752/11411261/cbdf2680-93ce-11e5-94da-2478cdf54a53.png)

Ich bräuchte Feedback, welche Teile davon gut, was nicht so gewünscht ist. Dann könnte ich detaillierte Varianten sketchen.

(Bezüglich der tl;dr Section bei einigen: Für einzelne Abschnitte der Info-Artikel würde es sich anbieten eine tl;dr Variante einzugeben, um das schnelle durchschauen nach Informationen zu erleichtern und es u.U. gesamt Verständlicher zu machen, Bsp. hier: [500px Terms](https://about.500px.com/terms/)  )

**Comment by sascha11110** [comment]
Danke für die klasse Entwürfe! Das bringt uns an der Stelle auf jeden Fall
schon mal ordentlich weiter.

Was mir dazu einfällt:
1) tl;dr Section (vor allem die Sätze am Rand in der Desktop Version) finde
ich an sich gut. Ich frage mich aber, wie aufwendig es ist, die Inhalte
dafür einzupflegen. Die 500px Terms Seite ist gerade wohl down...
1.5) Welche Funktion hat der Balken in 06 genau?

2) Die Aufteilung und vor allem die Navigation in 05 gefällt mir am besten.
Vor allem da die Icons sich ja auch in der App wiederfinden. Würdest du das
so auch in der mobilen Ansicht umsetzen? Soll die Navigation immer sichtbar
oder einklappbar sein?

3) Das große Bild in 02 und die Skyline in 04 finde ich nicht so gut, da
die beiden Elemente m.E. zu sehr vom Inhalt ablenken. Gerade bei der
Skyline denke ich auch, dass es schwer wird, die für jede Stadt zu bekommen.

4) Eine Kombination aus 03 und 05 kann ich mir vor allem für die
Desktop-Ansicht sehr gut vorstellen: Einfach den blauen Bereich aus 03 über
den rechten Bereich von 05 setzen.
4.5) Hast du dir den Titel im blauen Bereich aus 03 als Überschrift des
jeweiligen Inhalts oder als Benennung der Stadt gedacht?

5) Ich denke, 03 eignet sich auch sehr gut für die mobile Ansicht. Kommt
dann der App auch sehr nahe.

6) Ein Integreat-Branding könnte man in der Desktop-Ansicht jeweils fixed
am Seitenende rechts/links unterbringen. In der mobilen Ansicht auch und
dann nicht fixed. Vielleicht auch nur den Würfel im Header.

7) Die Positionierung der Sprachauswahl ist mir noch nicht ganz klar.

8) Eine Art breadcrumb hast du ja in der 01 schon vorgesehen. Gute Idee,
finde aber, dass die in der Form etwas oversized ist. Bezogen auf meinen
Punkt 4) vielleicht unter das Bild. Einfach eine Zeile mit hellgrauem
Background und ganz normaler Schrift.

9) Wie würdest du eine Startseite (Instanz und Sprache noch nicht gewählt)
aufbauen?

Thomas Weber <notifications@github.com> schrieb am Do., 26. Nov. 2015 um
00:47 Uhr:

**Comment by elordin** [comment]
Sorry für das lange Delay, Prüfungen und stuf...

Anyway:

1) Einpflege-Aufwand mal dahingestellt halt ich das ansonsten für inhaltlich sinnvoll, müsste man mal mit jmd. "von der Front" drüber reden. 
Vom Admin-Interface her wäre eine Möglichkeit der Umsetzung, dass man sich an die Events vom Editor dranhängt und dynamisch zu jedem Paragraph ein Textfeld daneben hängt für die TL;DRs

1.5) Querbalken nehme ich an!? Visuelle Abtrennung der einzelnen Abschnitte um um die Affordance zu bieten, dass der Textbereich klick-bar ist.

2) Bei entsprechender Bildschirmgröße immer anzeigen, wenn nicht genug Platz für den Content ist, ausblenden. Insbes. auf Mobile Devices wäre es aufgrund der geringen Breite sinnvoll nur begrenzt viele Level gleichzeitig anzuzeigen / anzudeuten und den Rest auszublenden.

4.5) Größter Titel sollte der Titel des aktuellen Artikels sein. Für die Orientierung ist das der wichtigste Teil. Die ausgewählte Stadt ändert sich deutlich seltener, entsprechend muss man sich diesbezüglich seltener re-orientieren.

6) Auf mobile devices / kleinen Größen wäre auch der untere Teil der Off-Canvas-Nav geeignet. Tendenziell da, wo Kontakt, Impressum etc. Links sind.

7) Sprachauswahl sollte am besten in den Header, vorzugsweise dauerhaft sichtbar.

8) Breadcrumb ist bei den meisten irgendwo mit drin, aufgrund meiner High-Fidelity Schrift nicht immer ganz gut zu erkennen ;). Top of the page, unterm Header oder unterm primären Titel sind alle gute Optionen für die Position.

9) 
Beide Aktionen, Sprache und Stadt wählen, würde ich full-single-page machen. 
Bei der ersten der beiden (Sprache nehme ich an) sollte noch mal kurz zusammengefasst sein, worum es auf der Seite überhaupt geht (ähnlich den Postern oder Flyern), sprachunabhängig bzw. in der häufigsten Sprachen.

Außerdem sollte ersichtlich sein, wer die Seite betreibt, zwecks Vertrauensbildung.

Bezüglich der Reihenfolge der Sprachen würde ich persönlich sagen deutsch und englisch sticky zu haben und den Rest der Häufigkeit nach sortiert zu haben. U.U. kann man die Accept-language des HTTP header auch noch in die Reihenfolge einfließen lassen.

Auf der Stadt-Auswahl-Seite sollte die Sprach-Auswahl noch relativ prominent sein, deutlicher als auf den folgenden. Hat man sich hier bereits vertippt sollte der Aufwand die Sprache noch einmal zu ändern möglichst gering sein, sonst führt das zu Frustration und Ablehnung.
Hat man bereits eine Stadt gewählt und ggf. auch einen Artikel ist die Schwelle die Seite zu schließen, weil man die Sprach-Option nich auf Anhieb findet geringer, da man ja bereits Inhalt gefunden hat.

Danach dann die Stadtauswahl. Sofern genug Platz ist sowohl mit Karte und Liste, wobei Interaktion mit der Liste die entsprechende Stadt auf der Karte hervorhebt und umgekehrt.
Auf der Karte evtl. Labels der Städte anzeigen abhängig davon, wie nah sich der Cursor zur Stadt befindet oder das, an der der Cursor am nächsten ist (Stichwort: Voronoi-Chart)
Sofern geolocation möglich ist die nächst gelegene Stadt highlighten, allerdings nicht die anderen Städte deswegen ausblenden.

**Comment by sven15** [comment]
@sascha11110 hat ein Design fertig. Können wir das Issue hier schließen?

**Comment by sascha11110** [comment]
Ja kannst du. Hatte das nur für mich zum nachschauen offen gelassen. Melde mich später noch zum Stand der WebView

Am 7. April 2016 00:18:09 MESZ, schrieb Sven <notifications@github.com>:
