### ISSUE TITLE
Übersetzte Seiten werden mehrfach angelegt 

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#229]
Zb wohnen in Augsburg taucht im englischen dann mehrfach auf

**Comment by Lemming0815** [comment]
Wo kommen die Übersetzungen überhaupt her?
Direkt von den Kommunen?

Mir fallen spontan crowd-sourcing Übersetzungsportale ein.
Ich hätte auch nen Kontakt zu einer Syrerin, die gern irgendwo helfen möchte. Gibt es noch Texte, die ins Syrische/Arabische übersetzt oder korrekturgelesen werden müssen?

**Comment by Meash** [comment]
In dem Fall automatisch, mir geht's bei dem Issue nur um unsere Software,
nicht Übersetzer Pool.

**Comment by Meash** [comment]
Looks like the trid is not yet set when the `on_save_post` is executed.
`$sitepress->get_element_trid($source_post_id, $wpml_post_type);` returns nothing.

**Comment by Meash** [comment]
WPML doesn't make it easy on this one:
The POST to connect translations comes from the client side in `post-edit.js`. This file also somehow sends a trid that is then used in the `ajax.php` (lines 554-579 `case 'connect_translations'`) to link the different versions.
I'll try to generate the trid on the server side and re-use the code that WPML implemented.

**Comment by sven15** [comment]
It does not seem that this happens very often. Prio set to low.

**Comment by sven15** [comment]
Can anyone confirm that this still happens? Otherwise I will close that issue soon.

**Comment by sven15** [comment]
Probably caused by the "duplicate" checkbox.
