### ISSUE TITLE
blog auf website wird nicht automatisch angezeigt

### ISSUE THREAD

**Issue by Lemming0815** [Integreat/cms#230]
auf der hauptseite integreat-app.de steht unter der überschrift 'blog' nichts. auch ein klick auf das top-menü ändert nichts daran. Nur der Link in der fußzeile funktioniert.

**Comment by sascha11110** [comment]
Danke für den Hinweis. Dafür muss wahrscheinlich das Theme leicht verändert werden. Ich kümmere mich drum.

**Comment by Lemming0815** [comment]
Nun ist es zwar über das top menü erreichbar, aber wird nicht beim runterscrollen automatisch als letztes item der seite angezeigt.
Außerdem ist in der standardansicht nichts dargestellt. Man muss im Blog selbst erst rechts einen Beitrag auswählen. Zumindest die letzten 2-3 Beiträge sollten angezeigt werden IMHO.

**Comment by dkehne** [comment]
Jetzt funktioniert!
