### ISSUE TITLE
Unwiderruflich löschen in UI entfernen

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#233]
Man kann gemäß #27 Posts nicht mehr endgültig löschen.

Beim Benutzer steht aber immer noch "Unwiderruflich löschen". Da sollten wir den Button auch noch entfernen. Analog zeigt WPML auch noch ein "delete permanently" an.

**Comment by sven15** [comment]
Hat sich inzwischen erledigt?! Oder gibt es noch irgendwo einen Link, den man "beschönigen" muss?

**Comment by Meash** [comment]
Sind die beiden eingangs erwähnten Button Texte angepasst?

**Comment by sven15** [comment]
Man kann Seiten halt nicht mehr aus dem Papierkorb leeren. Der Link ist nicht mehr existent.

**Comment by Meash** [comment]
Aso I see. Einzelne Seiten auch nicht?
Dann gibt's bei WPML noch das "delete permanently", das sollte auch noch
weg.
Am 07.04.2016 11:56 vorm. schrieb "Sven" <notifications@github.com>:

**Comment by sven15** [comment]
Kann ich nirgendwo finden ... In der Seitenübersicht unter dem Menüpunkt WPML gibt es auch keinen Löschen Link.

**Comment by Meash** [comment]
Grep mal danach im Code
Am 07.04.2016 12:12 nachm. schrieb "Sven" <notifications@github.com>:

**Comment by sven15** [comment]
Issue cannot be confirmed anymore.
