### ISSUE TITLE
PDF-Creator Error nach Drag&Drop Bild einfügen

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#240]
Habe ein Bilder auf einer Seite via Drag & Drop in den Text gezogen und nicht über "Dateien hochladen". Danach hat der PDF-Creator keine Lust mehr gehabt:

Kann das jemand reproduzieren und den Fehler eliminieren?
![bug1](https://cloud.githubusercontent.com/assets/4182469/11531536/dcf38ac2-98fd-11e5-9650-12b0060e9cbb.JPG)

**Comment by pblanz** [comment]
Ich habs gerade versucht, in ne beliebige Seite ein Bild vom Browser in den Editor gezogen , gespeichert, geupdated und dann ne PDF davon geniert (deutsche Sprache). Hat ohne Probleme funktioniert.
