### ISSUE TITLE
Return non-live instances with flag

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#242]
All instances shall be returned from now on to be able to present them in the municipality.
However, only live instances should be seen.
Therefore, return a flag `live` with each instance that is set to true when the instance is live and false when not.

Since this breaks existing functionality (all existing apps would see all instances since they ignore the parameter), do this in a new API version `v1`.

**Comment by Dalanie** [comment]
what do you mean by api version v1 ? is the address changing?
it won't break anything in android  ;)

please implement as soon as possible

**Comment by Meash** [comment]
@Dalanie it *will* break existing apps because they will display all instances instead of only the live ones. Hence the upping of the version number.
