### ISSUE TITLE
Formatting of inserted text

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#243]
When inserting text e.g. from word, we should only adopt the formatting that can also be used in the text editor.

**Comment by Meash** [comment]
@dkehne wie kann man das reproduzieren? Welcher Text aus Word zb wird bei uns falsch formatiert und wie sollte er richtig aussehen?

**Comment by dkehne** [comment]
Ich glaube das hängt stark hiermit zusammen und hat gar nicht so viel mit Input aus Word zutun: 

https://github.com/Integreat/cms/issues/299

**Comment by sven15** [comment]
Assigned @FritjofK to find someone for solving this issue. We should implement this, especially because we do not support tables anymore.

**Comment by sven15** [comment]
http://stackoverflow.com/questions/12027137/javascript-trick-for-paste-as-plain-text-in-execcommand

**Comment by sven15** [comment]
Even better: https://wordpress.org/plugins/advanced-tinymce-configuration/
