### ISSUE TITLE
Simplify page editing

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#244]
disable:
* indents
* insert as text
* remove formatting
* symbols
* smileys
* read more
* top menu bar
* text editor
* visibility

implement:
* underline

**Comment by pblanz** [comment]
Ist das hier noch aktuell? Folgende Vorschläge:
<ol>
<li>U (underline) kann man noch zu den angezeigten Symbolen, rechts neben B (bold)</li>
<li>remove link Button entfernen</li>
<li>Menue sollt</li>
<li>Tools menu entfernen/verstecken/nur für admins anzeigen</li>
<li>Blocksatz mit zur oberen Menüleiste dazunehmen (ist immo in der erweiterten Werkzeugleiste) </li>
</ol>

Vielleicht wäre auch ein dummy-guide gut, der die wichtigsten Funktionen erklärt?

**Comment by sascha11110** [comment]
zu 1.) agree

zu 2.) Wenn man den "remove link" Button entfernt, sollte man m.E. die
Funktion in den Button "add link" integrieren.

zu 3.) ?

zu 4.) würde ich so drin lassen. Man kann das Icon vielleicht etwas
verständlicher machen. Siehe auch: a)

zu 5.) agree

a) Thomas hat da schon einen sehr guten Entwurf gemacht... bezieht sich
allerdings auf das gesamte CMS. Findest du im Drive unter "\Medien &
Grafiken\Mockups\CMS".

b) An einem Guide bin ich dran. Ich hoffe, dass ich das Ding jetzt auch
langsam mal fertig bekomme.

pblanz <notifications@github.com> schrieb am Mo., 28. Dez. 2015 um
16:50 Uhr:

**Comment by pblanz** [comment]
also ich hab nen kleines Plugin geschrieben, welches die gewünschten Änderungen umsetzt. Ich hoffe da gibts keine Konflikte mit dem Guide @sascha11110 , @Meash ? Nicht das du im Guide Buttons erklärst die es nicht mehr gibt/die jetzt wo anderst sind.

**Comment by sascha11110** [comment]
Bis jetzt sind noch keine Inhalte im Guide

pblanz <notifications@github.com> schrieb am Mi., 20. Jan. 2016 12:33:

**Comment by pblanz** [comment]
Ich hab das Zeug, was man (meiner Ansicht nach) normalerweise nicht braucht aus der ersten Tool-Leiste rausgeschmissen und in die zweite gepackt.

Hier mal ne preview:

NEW:
![editor_new_extended](https://cloud.githubusercontent.com/assets/14991786/12450035/91f6109e-bf81-11e5-9c44-9c0069a025e3.PNG)


OLD:
![editor_old_extended](https://cloud.githubusercontent.com/assets/14991786/12451103/be9d6d26-bf87-11e5-9b02-b791cb896aad.PNG)

**Comment by dkehne** [comment]
Japp finde ich gut! :)

**Comment by Meash** [comment]
Mir ist noch aufgefallen, dass die Kontrollen für Bündigkeit (links zentral
rechts) über zwei Zeilen verteilt sind, die gehören imo zusammen
Am 20.01.2016 16:20 schrieb "Daniel Kehne" <notifications@github.com>:

**Comment by pblanz** [comment]
Ok, dann würd ich die alle eher nach unten verschieben. Ich dachte das man blocksatz/alignleft eher braucht als alignmidle/alightright

**Comment by Meash** [comment]
Vlt können wir uns auch an Word orientieren, das kennen die Leute schon

**Comment by pblanz** [comment]
Gute Idee, bei Word schauts so aus:

![word](https://cloud.githubusercontent.com/assets/14991786/12457903/684c539a-bfa7-11e5-8ccd-16e9ec37b3df.PNG)

**Comment by pblanz** [comment]
Ich schau mal wie ich das so hinbiegen kann :)

**Comment by Meash** [comment]
Gibt's da eigentlich keine Plug-ins von Leuten, die sich daran auch stören? Wenn nicht, können wir unseres vielleicht auch irgendwann bei WordPress reinstellen

**Comment by sascha11110** [comment]
Kann man doch eigentlich alles in der Settings Page von dem TinyMCE
Advanced einstellen oder?

Martin Schrimpf <notifications@github.com> schrieb am Mi., 20. Jan. 2016 um
22:17 Uhr:

**Comment by pblanz** [comment]
ja, man kann dort einiges einstellen, aber Beispielsweise den underline Button hab ich dort nicht gefunden. Und wenn man mal den dreh raus hat, kann man das easy über das plugin machen. Zudem lassen sich über das Plugin noch weitere einstellungen vornehmen, in dem man  filter/actions des tiny_mce hookt.
