### ISSUE TITLE
todo-translation pages show 100+ times in pages tree view (Augsburg)

### ISSUE THREAD

**Issue by Lemming0815** [Integreat/cms#245]
there is a page, which shows up more than 100times in the pages>treeview section. but not under pages>all pages.
For now, it seems only possible to delete them one by one.
Its cluttering the overview and my suspicion is, it also slows down the database.

"all published pages" shows over 700 pages but under all languages, one can only see 135. I wonder where those missing 550 pages are.

**Comment by Lemming0815** [comment]
these pages don't seem to have a status. cms-tree-page-view is showing them because it's showing all pages independent of status (except trash). The core module isn't. 
Is it a bad idea to change the core module?

**Comment by Meash** [comment]
This was already resolved in 19ece45b971ce0e51a91bc5e47582deed76bcf07.
PS: don't change any third-party code as per https://github.com/Integreat/cms/wiki/Modification-of-third-party-code
