### ISSUE TITLE
PDF-Creator druckt keine Bilder

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#253]
Das Demokratie-Leben Logo aus dem Kapitel "Willkommen in Augsburg" wird z.B. nicht gedruckt.

**Comment by pblanz** [comment]
Ich hab lokal keine Probleme damit.

**Comment by Meash** [comment]
@dkehne kannst du das auf dem [Testsystem](http://vmkrcmar21.informatik.tu-muenchen.de/wordpress_test/augsburg/wp-admin/) reproduzieren?

**Comment by dkehne** [comment]
Ich prüfe das.

**Comment by dkehne** [comment]
Ja kann ich. Also wenn ich im Testsystem den Guide drucke, sollte auf Seite 1 "Willkommen in Augsburg" auch das demokratie leben logo sein. Ist es aber nicht.

-- testinstanz, augsburg, deutsch

**Comment by pblanz** [comment]
Ok, ich schaus mir an.

**Comment by pblanz** [comment]
Also das Problem scheint das width-attribut im image tag zu sein. TCPDF kommt mit width = "100%" nicht klar. Ich nehm die 100% bei allen Bildern raus und überleg mir ne alternative für das scaling.

**Comment by Meash** [comment]
Zu dem width Tag gibt es auch noch ein Issue. Wordpress setzt das bisher
automatisch, sollte man rausnehmen. Das löst dann auch dieses Issue.

**Comment by dkehne** [comment]
Funktioniert!
