### ISSUE TITLE
Table-Plugin WordPress

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/cms#254]
http://wpdatatables.com/ - could you validate whether or not this plugin would make sense? Tables are always a problem on the client side...

**Comment by dkehne** [comment]
Warum ist das wieder auf @Meash ?

**Comment by Meash** [comment]
Was meinst du? Das issue ist nicht erledigt und wurde nie geschlossen. Wenn du das `Closed` oben meinst, das gehört zu dem referenzierten Issue 255.

**Comment by sven15** [comment]
Das Plugin wäre aber nur für den Webview interessant? Und ich glaube, dass da die Tabellen kein Problem sind. Tendiere dazu, dieses Issue zu schließen.

**Comment by Meash** [comment]
Nein, es geht darum dass zb keine Tabellen Header möglich sind momentan. Und die Tabellen teilweise wohl komisch formatiert werden

**Comment by sven15** [comment]
Dh wir müssten Tabellen-Rohdaten im Page-Quelltext mitliefern, die wir in der App selbst "rendern"? Habe Zweifel was Kosten- / Nutzenverhältnis derzeit angeht. Wäre eher was für die längere Zukunft.

**Comment by mschrimpf** [comment]
Der App-Viewer sollte HTML korrekt darstellen - sprich wenn die WordPress tables tatsächlich als `<table>` gebaut werden würden und sich darin `<thead>` und `<tbody>` finden, sollte das korrekt gerendert werden. Also app-seitig gehe ich davon aus, dass man nichts ändern muss - sollten wir aber validieren, falls wir das angehen.

**Comment by sven15** [comment]
Tabellen gibts nicht mehr.
