### ISSUE TITLE
wordpress 4.4 update

### ISSUE THREAD

**Issue by Lemming0815** [Integreat/cms#255]
Does anyone see a reason why we shouldn't update the backend to wordpress 4.4 (released today I think)?
Apparently, it is a bit more responsive and easy on resources.
Also, list tables display on all size screens ought to be improved. Might be related to #254 
Any other ideas why we should or shouldn't update?

Changelog: https://codex.wordpress.org/Version_4.4

**Comment by sascha11110** [comment]
I don't mind... but it is important that the plugin WP REST API is updated
at the same time because in 4.4 it is integrated in wordpress core. The
plugin update prevents any resulting conflicts.

Martin <notifications@github.com> schrieb am Fr., 11. Dez. 2015 um
21:07 Uhr:

**Comment by Meash** [comment]
Do it but double-check that everything works smoothly, especially the REST API as mentioned by @sascha11110.
