### ISSUE TITLE
PDF-Creator creates pages which are too large

### ISSUE THREAD

**Issue by pblanz** [Integreat/cms#258]
see image
![too_large_pages](https://cloud.githubusercontent.com/assets/14991786/11815105/7ef0561a-a34a-11e5-835b-fb62bd99b108.PNG)

**Comment by pblanz** [comment]
Fixed it

**Comment by Meash** [comment]
Thumbs up! Where's the pull request? :D

**Comment by pblanz** [comment]
Coming soon, I'll try to fix other pdf creator bugs, too

**Comment by pblanz** [comment]
resulved in 46148e6cc9fdac65465ea6c4894d2c3403e106ed
