### ISSUE TITLE
Deleting a page and adding new translation destroys WPML linking

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#259]
After moving an article to trash and adding a new translation, the linking to the original article is not working.

Workaround: empty trash and then add translation.

**Comment by Meash** [comment]
Duplicate of #257?

**Comment by pblanz** [comment]
What do you mean by structure? Are you referring to \<div>'s, \<table>s and such? Can you give an example of a page where this happens?

**Comment by sven15** [comment]
I do not think of this as a bug anymore. It's just something you have to know as a user. I will close this issue for now. Reopen it, if you feel it's necessary to fix it.
