### ISSUE TITLE
Always copy media in translated pages

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#260]
When a site is created, the checkboxes to copy media attachments to translated sites are automatically checked.
However, when editing a page, these checkboxes are not checked:
![unbenannt](https://cloud.githubusercontent.com/assets/4182469/11716437/2e36db26-9f4a-11e5-9da7-8c43c7e4b9b2.JPG)

We should always synchronize media attachments between languages -> hide the checkbox and have it always checked.

related to #244

**Comment by dkehne** [comment]
@sven15 kannst du das als Quick-Win fix einbauen?

**Comment by sven15** [comment]
There is no hook for this, the checkboxes need to be hidden via JavaScript. I don't like this solution.
