### ISSUE TITLE
Icons initial bereitstellen inkl. Lizenz-Verweis

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#267]
Die Icons aus dem Google Drive unter "Medien und Grafiken" -> "Icons" sollen in jeder erzeugten Instanz in einem eigenen Medienordner(!) verfügbar sein. Dazu muss ins Impressum der Satz "Die Icons wurden bereitgestellt von www.flaticon.com"

**Comment by Meash** [comment]
Für neue Instanzen reicht es, wenn die Icons in den Basis-Instanzen `Deutschland` und `Empty Base Instance` bereitgestellt werden. Für jede neue Instanz werden die Daten entsprechend dupliziert.
