### ISSUE TITLE
Handling sites that go from "publish" to "draft"

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#273]
Options:

1. consider them as "trash" -> old published version is deleted although one might only want to change a minor detail
2. ignore the change -> working around deleting a page and keeping them as a draft instead no longer works.

I would personally opt for option 2 since I don't find it reasonable to consider already published pages as trash.

**Comment by Dalanie** [comment]
Option 2 would require an updated page with a new timestamp so that the clients will be notified

**Comment by dkehne** [comment]
was genau heißt das? "ignore the change -> working around deleting a page and keeping them as a draft instead no longer works."? Das Problem ist das folgende: Jemand will erstmal nur 2 von 9 Seiten aus dem Global Template freigeschaltet haben, weil er die Lösung möglichst schnell braucht und bereit bei 2 Seiten den Content aufgefrischt hat. Die anderen 7 Seiten aus dem Global Template werden nach und nach veröffentlicht (sobald sie mit den weiteren Infos angereichert sind). Macht es eventuell Sinn alle Seiten aus dem Global Template per Default erstmal nur auf "Entwurf" zu haben?

**Comment by Dalanie** [comment]
Reden wir vom gleichen?!

Mir gehts es darum dass jegliche Aenderungen von Seiten, frei geschaltet/geloescht/gesperrt an den Client propagiert werden muessen - und das ist derzeit nicht der Fall. Ich verstehe beide Ansaetze nicht :)

**Comment by dkehne** [comment]
Mir gehts darum, dass Seiten die gelöscht oder im Modus "Entwurf" sind nicht in der App angezeigt werden. Sprich wenn jemand den Status im CMS von veröffentlicht in etwas anderes ändert, wird die Seite in der App gelöscht bei der nächsten Aktulaisierung

**Comment by Dalanie** [comment]
Dann reden zumindest wir beide vom gleichen

**Comment by Meash** [comment]
Genau das finde ich aber komisch. Nehmen wir an, ich mache eine neue Seite und publishe diese. Daraufhin wird sie in der App angezeigt. Dann fällt mir ein, ich will ein kleines Detail ändern, werde damit aber nicht fertig und setze den Status auf Entwurf. IMO sollte die Seite weiterhin in der App angezeigt werden.

Der einzige Use-Case für "keine Entwurfs-Seiten anzeigen" ist doch, dass sie in Instanzen anfangs nicht angezeigt werden sollen, die aus dem Global Template befüllt wurden. Die mMn saubere Lösung ist, die Seiten einfach zu löschen. Man kann sie aus den Revisionen ja nach wie vor wiederherstellen.

**Comment by dkehne** [comment]
Mhh boar das finde ich aber bei dem Community-Gedanken auch bedenklich. Vor allem wenn viele an dem System arbeiten gibts aufeinmal Entwurfs-Seiten und man weiß gar nicht woran man jetzt veröffentlichte erkennt und woran nicht. Dann fangen die auf einmal an Sachen zu löschen und erstmal in ihrem lokalen Word zu überarbeiten. Lasse mich aber auch gerne von was anderem überzeugen.

Ich wäre für ein einfaches WYSIWYG - App und CMS. Außer wenn CMS auf "Entwurf" steht statt auf "Veröffentlicht".

**Comment by Meash** [comment]
So kollaborativ dass viele daran arbeiten, sind wir noch nicht ;-)
Wie würdest du dann mit Seiten gemäß dem oben beschriebenen Szenario umgehen? Von publish auf draft?

**Comment by sascha11110** [comment]
VIelelicht kann man auch, sobald die Seite auf "Entwurf" gesetzt wird, ein
PopUp anzeigen, in dem gefragt wird, ob der bisherige Stand der Seite
trotzdem in die App oder vorerst ganz raus soll.

Martin Schrimpf <notifications@github.com> schrieb am So., 17. Jan. 2016 um
22:52 Uhr:

**Comment by Meash** [comment]
Sascha, finde den Vorschlag gut, fürchte aber dass das für den Verwalter zuviel zum Einstellen wird.
Haben gerade in Skype gebrainstormed und uns auf eine Umbenennung des Papierkorbs geeinigt (siehe referenziertes Issue).
