### ISSUE TITLE
"Löschen" umbenennen in "Ausblenden"

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#274]
Der Papierkorb sorgt für etwas Verwirrung (zb #273) - intuitiver ist, die Seiten auszublenden.
Umbenannt werden sollen also "Löschen" und "Papierkorb" (und was noch dazu gehört, was ich gerade vergesse ;) - also auch etwas Analyse notwendig).

**Comment by sven15** [comment]
Allgemein produziert der Papierkorb Probleme. Wenn man eine Übersetzung in den Papierkorb legt, dann erstellt WPML bei Klick auf "+" eine neue Übersetzung, kann sie aber nicht linken, da die alte noch verlinkt ist. Oder so. Jedenfalls hat es in Bad Tölz zu derben Problemen geführt.

**Comment by Meash** [comment]
Neues Issue dafür bitte :o)

**Comment by sven15** [comment]
The analysis was wrong. The duplicate translations were created by the "duplicate" checkbox.
Renaming the "remove" link to "hide" is fine.

**Comment by sven15** [comment]
The link is called "In den Papierkorb" legen. I think that this is clear enough. Most users are used to the concept of a trash bin.
