### ISSUE TITLE
Clickguide broken Overlay

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#287]
![clickguide-buggy](https://cloud.githubusercontent.com/assets/5308236/12445783/a43fc198-bf66-11e5-811f-80c7ee38f314.PNG)

Browser: Chrome 47.0.2526.111 m
OS: Win10

**Comment by sascha11110** [comment]
Change presentation.css:3 to "z-index:999999;"

**Comment by sascha11110** [comment]
Solved by #295
