### ISSUE TITLE
Fire warning when site is located on third level or higher

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#292]
Fire a warning when site is located on third level or higher: is not shown in the menu structure of integreat app
![third-level](https://cloud.githubusercontent.com/assets/15168372/12478668/69018b04-c036-11e5-934d-c8d2f66909e1.jpg)

**Comment by Meash** [comment]
We should consider whether we want to leave total freedom to our users and only warn them orally or if we want to implement a "don't do this" warning.
Should we choose the warning, [admin_notices](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices) is the way to go.
