### ISSUE TITLE
Problems with Autotranslation-Button in Cölbe-Instanz

### ISSUE THREAD

**Issue by FritjofK** [Integreat/cms#296]
Hab den Autotranslate-Button für die Cölbe-Instanz ausprobiert. Reihenfolge im Deutschen wird leicht verändert und Französische Übersetzung erscheint im Deutschen. Ist noch nicht wieder aufgeräumt und kann in der Cölbe-Instanz angeschaut werden, wie das aktuelle Resultat ist.

**Comment by Meash** [comment]
Autotranslate ist erstmal wieder deaktiviert.

**Comment by dkehne** [comment]
Also so sieht das aus bei Seiten wo es funktioniert: 
![unbenannt](https://cloud.githubusercontent.com/assets/4182469/12551654/60fe285c-c36c-11e5-9b82-e1f55e40e0dd.JPG)

da steht "dupliziert" hinter den pages. bei anderen steht kein dupliziert und da werden auch blder nicht übernommen. das ist nochmal ein problem in der cölbe-instanz zusätzlich zu den verschiebungen die fritjof genannt hat

**Comment by sven15** [comment]
I'm not able to find a definite way of replicating this bug. It seems to be related to the trash bin in some way. I suggest to re-enable the button and to focus on clean templates and enforcing a clean page and translation structure. One way to go would be to allow only writing german pages and then adding translations from there.

**Comment by sven15** [comment]
Workaround: alle Kategorien / Überschriften-Pages erneut "Veröffentlichen". Ich prüfe gleich, wo die Veränderungen in der Datenbank sind.

**Comment by sven15** [comment]
Fixed with 1fa4f051dda863060efb0d3f557223962fa8e892
