### ISSUE TITLE
Multilingual label text

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#297]
We have some labels that are single language, we should use [POT files](https://codex.wordpress.org/I18n_for_WordPress_Developers#POT_files) to add multi-language capability.

Labels that are not translated at all so far (feel free to add more items):
- [Automatic Translation Button](https://github.com/Integreat/cms/blob/acf36da34a1012c7cd70ba3023541ee7ec84b06b/wp-content/plugins/automatic-translation-button/js/automatic-translation-button.js#L7)

Note: pot text is generated on the server (PHP), not on the client side. So don't get confused by the JavaScript files, they will need to use values that are generated by PHP.

**Comment by sven15** [comment]
Useful for #425

**Comment by sven15** [comment]
We have to translate a string in a .js file. Either we move the few JS lines into PHP or load the string via REST. Is one button worth the effort? :-D

**Comment by svenseeberg** [comment]
The automatic translation button is not important as long as the automatic translation is not working. see #523

**Comment by svenseeberg** [comment]
Automatic translation is deactivated (for now).
