### ISSUE TITLE
Listen- und Tabellen

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#298]
Hier gibt es teilweise Probleme mit dem Listensymbol (Punkt, Strich), der nicht auftaucht und der Zeilenabstand bei der Liste passt zum Teil nicht.

**Comment by Meash** [comment]
"Teilweise Probleme" / "zum Teil" ist nicht reproduzierbar. Bitte genaue Angaben

**Comment by FritjofK** [comment]
Will be cloed due to no news within last three months
