### ISSUE TITLE
Zeilenabstand

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#299]
Der Zeilenabstand weicht zwischen CMS-Editor, dem WYSIWYG-Vorschau-Smartphone und der realen Umsetzung auf der App ab. Die Stadt Augsburg hilft sich gerade in dem sie immer DIV-Tags um die Blöcke macht, dann klappt es wohl manchmal. Das WYSIWYG-Vorschau-Smartphone "lügt" wohl auch in dem Sinne, dass nach dem Speichern die Formatierung nochmal geändert wird.

**Comment by sven15** [comment]
Das werden wir wohl nie 100% in den Griff bekommen. Nicht zuletzt weil Smartphones unterschiedliche Größen und Textzoom haben. Die Frage ist, ob wir das issue schließen oder als Erinnerung da lassen, dass wir da eine gewisse Konvergenz anstreben sollten.

**Comment by Meash** [comment]
Was wir zumindest machen sollten, ist CSS und JavaScript zwischen App und Preview abzugleichen. Vielleicht gibt es ja auch eine Möglichkeit, die WebView von Android/Xamarin zu emulieren... @Dalanie was denkst du?

**Comment by dkehne** [comment]
Das hier kam als Feedback:

Ein weiteres Problem ist mir aufgefallen, der Zeilenabstand bei Umbrüchen im visuellen Editor. Wenn ich z.B. eine Adresse eingeben möchte sind die Zeilenabständen, in der App, zu groß. Beim Umwandeln des visuellen Textes in den HTML Code werden einfache Zeilenumbrüche übernommen und zusätzlich der Tag <br /> eingefügt. Dies ignoriert zwar der Browser am PC aber nicht die App welche dann eine zusätzliche Leerzeile anzeigt. Kopiert man den Quelltext (Werkzeuge -> Quelltext) in den Text Editor ist die Darstellung korrekt.
Problematisch hierbei, öffnet man eine Seite, welche zuvor im Text Modus bearbeitet wurde, im Visuellen Editor und speichert diese ab stimmen die Zeilenabstände nicht mehr.

Da ich den Sachverhalt nicht gut erklären kann, hier ein Beispiel:

Gebe ich im Visuellen Editor folgendes ein:

Max Mustermann
Musterstraße 00
00000 Musterhausen

ergibt das den HTML Code:

<p>Max Mustermann<br />
Musterstraße 00<br />
00000 Musterhausen</p>

In der App wird zwischen den Zeilen eine weitere Zeile dargestellt.

Gebe ich obigen Code direkt in den Text Editor ein und entferne die Zeilenumbrüche (<p>Max Mustermann<br />Musterstraße 00<br />00000 Musterhausen</p>) ist die Darstellung richtig.

Wenn man es weiß, lässt sich das Problem relativ einfach, per kopieren des Quellcodes, umgehen daher benötige ich keine Antwort von Ihnen, dies ist eher als Hinweis gedacht sofern Ihnen das Problem noch nicht bekannt sein sollte.

**Comment by sajjadalisiddiqui** [comment]
This only happens when you use Google Chrome browser? Tried with Firefox? @dkehne

**Comment by sven15** [comment]
As described in #40: use wpautop() for preview.
