### ISSUE TITLE
PDFs im CMS nicht offline availabe

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#302]
Scheinbar ging das mal, jetzt aber wohl nicht mehr. Testweise kann dazu das Kapitel "Wichtige Dokumente" aus der Augsburg-Instanz herangezogen werden. Dort liegen z.B. ein Zahnarzt-dokument und ein Essensgutschein. Diese sind als PDF hochgeladen worden ins CMS und sollen Offline-Verfügbar sein (so wie alle Medien die hochgeladen werden)

**Comment by Meash** [comment]
Was hat das mit dem cms zu tun?
In der App ist das Issue bereits offen, wenn es darum geht.

**Comment by Meash** [comment]
Duplicate of Integreat/app-android#123
