### ISSUE TITLE
REST API: Return page url

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#304]
Based on Integreat/app-android#155, the REST API should also return the frontend url for all modified_content (pages/events as of now).

See https://github.com/Integreat/cms/blob/develop/wp-content/plugins/wp-api-extensions/endpoints/v0/RestApi_ModifiedContent.php#L199

**Comment by Dalanie** [comment]
Any progress on this ticket? Might be useful for Android

**Comment by pblanz** [comment]
Ich kümmer mich heute darum.

**Comment by pblanz** [comment]
Also, ich hab den Permalink mit ins JSON genommen (key: Permalink). Bsp.:

"id": "321",
**"permalink": "http://localhost/wordpress/augsburg/de/inanspruchnahme-von-dolmetschern-uebersetzern/aemterlotsen/"**,
"title": "Ämterlotsen",
"type": "page",
"status": "publish",
"modified_gmt": "2015-10-10 10:41:40",
"excerpt": "Wenn Sie einen Dolmetscher benötigen, wenden Sie sich an eine der Asylberatungsstellen oder direkt ...
"content": "<p>Wenn Sie einen Dolmetscher benötigen, wenden Sie sich an eine der Asylberatungsstellen oder direkt an die ...
"parent": "57",
"order": "0",
"available_languages": {"fr":550},
"thumbnail": null,
"author": {"login":"kehne","first_name":"Daniel","last_name":"Kehne"}

**Comment by pblanz** [comment]
ist es das was du brauchst?

**Comment by Dalanie** [comment]
Reicht aus, wenn die links in den Texten genau diesen link beinhalten! Kann
auch kürzer werden (falls möglich), also nur der relative Pfad zum Beispiel

**Comment by pblanz** [comment]
In welchen Texten? Ich hol mir die URIs serverseitig über die ID. Und was meinst du mit dem relativen Pfad? Soll ich den bereits serverseitig rausparsen und mitschicken? Ich bekomm über die ID immer den absoluten Pfad (die absolute URL).

**Comment by Meash** [comment]
Hintergrund dieses Tickets ist, dass Crosslinks in den Inhalten nicht den Browser öffnen sollen, sondern weiterhin in der App navigieren (zb eine Verlinkung von "Familie" auf "Gesundheit").
Wichtig ist also, dass die Crosslinks und die permalinks übereinstimmen.

Am zukunftssichersten (zb bei Domain-Wechsel) wäre es wahrscheinlich, wenn wir überall mit [relativen Pfaden](http://wordpress.stackexchange.com/a/32729/80162) arbeiten - oder muss die App bei einem Domain-Wechsel sowieso alles resetten @Dalanie?

**Comment by pblanz** [comment]
Ok, Danke! Ja, es kommt halt ganz drauf an wie die Querverlinkungen eingegeben werden. Diese [Seite](https://codex.wordpress.org/Linking_Posts_Pages_and_Categories) nennt neben Permalinks nur noch eine andere Möglichkeit für interne Verlinkungen, über die page-ID. (Bsp.: "\<a href="/index.php?p=123">Post Title</a>"). 
Diese URL kann man sich auch aus der DB ziehen und mitschicken. (
"guid
    (string) A link to the post. This is not the permalink. To get the permalink use get_permalink. ")
s. [hier](https://codex.wordpress.org/Function_Reference/$post)

@Dalanie , wie wird denn Client-Seitig ein link behandelt? Reagiert die App erst beim Klick auf den link und redirectet dann entsprechend oder hast du vor, den Content im voraus zu parsen um links für die internen Querverlinkungen anzupassen.

Eine Möglichkeit wäre auch, wenn man ein Label-Attribut mit der ID des Zieles in den anchor Tag speichern könnte? etwa (\<a href=" ... " label="1234">...)

**Comment by Dalanie** [comment]
Ich moechte am liebsten nichts parsen. Ich reagier auf den Klick und schaue
dann, ob die Seite eventuell als 'Page' vorliegt, basierend auf der JSON
die ich bekomme. Ich brauch also ne JSON-Property: URL und bei den Hrefs
muss ebendiese url drin stehen ;)

**Comment by pblanz** [comment]
Ok, dann kannst du ja auf den Permalink und auf die Page-ID vergleichen, oder? Die andere URL schmeiß ich noch ins JSON mit rein. Hältst du dir dann lokal ne Hashmap o.ä. mit  allen Verlinkungen? Im Falle von links mit einer relativen URL (obwohl ich in Wordpress-Pages noch keine gesehen habe) könnte man ja sowas wie "longest prefix matching" machen.

**Comment by Dalanie** [comment]
klingt gut!

**Comment by pblanz** [comment]
So, hab etwas besser recherchiert. Es gibt viele verschiedene Möglichkeiten eine Wordpress-page zu verlinken. Vor allem auch je nach rewrite-rules. Die sollten halt nicht geändert werden! Naja, ich hab jetzt mal eine von Wordpress vorgeschlagene default list für permalinks hergenommen und schick die im JSON mit. Das sieht dann so aus:

{
    "id": ​266,
    "permalink": 
{
    "url": "http://localhost/wordpress/muenchen/de/kategorien/",
    "url_site": "http://localhost/wordpress/muenchen",
    "url_page": "kategorien",
    "url_page_id": "http://localhost/wordpress/muenchen/de/veranstaltungen/kategorien/",
    "url_date_1_name": "http://localhost/wordpress/muenchen/2015/10/17/kategorien",
    "url_date_2_name": "http://localhost/wordpress/muenchen/2015/10/kategorien"
},
"title": "Kategorien",
"type": "page",
"status": "trash",
"modified_gmt": "2015-10-17 20:01:26",
"excerpt": "CONTENTS",
"content": "<p>CONTENTS</p>",
"parent": ​0,
"order": ​0,
"available_languages": [ ],
"thumbnail": null,
"author": 
    {
        "login": "schrimpf",
        "first_name": "Martin",
        "last_name": "Schrimpf"
    }
}

**Comment by Dalanie** [comment]
Sind url date 1 und url date 2 dynamisch hinzugefügt oder gibt es immer
genau die zwei?

**Comment by pblanz** [comment]
WP bietet diese zwei per default an:

https://codex.wordpress.org/File:permalink-settings.png

**Comment by Dalanie** [comment]
Closed? Ich sehe die Änderungen noch nicht:
http://vmkrcmar21.informatik.tu-muenchen.de/wordpress/augsburg/de/wp-json/extensions/v0/modified_content/pages?since=2014-12-31T16%3A00%3A00-0800

v1 findet er nicht

**Comment by Meash** [comment]
Bisher nur auf wordpress_test, mit dem nächsten Master merge dann auch live.

**Comment by Dalanie** [comment]
ZzzzzZ

**Comment by Meash** [comment]
Haben leider immer noch keinen guten Prozess gefunden, wie wir Änderungen
zuverlässig testen können
Am 23.02.2016 07:33 schrieb "Daniel Langerenken" <notifications@github.com>:
