### ISSUE TITLE
Einige Beiträge können nicht in den Papierkorb verschoben werden

### ISSUE THREAD

**Issue by FritjofK** [Integreat/cms#306]
In der Deutschland-Instanz sind einige Seiten drin, die nicht in den Papierkorb verschoben werden können (z. B. Unterbringung). 

https://github.com/Integreat/cms/issues/296

Ist das Problem, das in dem Issue von Daniel gezeigt wurde, mit den Seiten, wo bei den Übersetzungen duplizieren hintersteht. Beitragsbild wird zwar übernommen, aber die Übersetzung mit dem Deutschen Text überschrieben.

**Comment by sven15** [comment]
Ich bitte um mehr Informationen, da ich derzeit nicht in der Lage bin, das Problem einzugrenzen.

**Comment by sven15** [comment]
Möglicherweise verwandt mit #307 ?

**Comment by sven15** [comment]
knier kann nicht artikel Unterbringung in Deutschland-Instanz löschen.

**Comment by sven15** [comment]
Not fixed.
