### ISSUE TITLE
Store backups on Integreat servers 

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#309]
So far, our backups are stored on @bengin's servers. This makes it harder to restore backups since we need Bengin to access them.

Instead, we should store them on one of the organization's servers so that more people can access them and it is no longer dependent on a single person.

**Comment by sven15** [comment]
Done. 2x täglich wird auf dem 79er ein dump angelegt und 14 tage aufgehoben.

**Comment by Meash** [comment]
File backups auch? Zumindest für die Dateien, die nicht gleich sind wie auf
dem Master branch (konkret zb Datenbank Zugangsdaten)

**Comment by sven15** [comment]
nein, bisher nur ein dump der wordpress database. ich denke darüber nach, wie wir das /var/www/html/cms directory sinnvoll synchronisieren und sichern können.

**Comment by Meash** [comment]
Auch nochmal nachgedacht: würde doch alles sichern, weil git Status Dateien
in der gitignore ignoriert (das sind zb alle uploads).
Man könnte alternativ auch `git clean -ndX` ausführen, um sich alle
geänderten Dateien Listen zu lassen.

**Comment by sven15** [comment]
Low hanging: incremental backups with http://www.nongnu.org/rdiff-backup/examples.html, for example to vmkrcmar79.

**Comment by sven15** [comment]
done with duply from vmkrcmar21 to 79
