### ISSUE TITLE
Replace regular SQL statements with prepared statements

### ISSUE THREAD

**Issue by pblanz** [Integreat/cms#313]
In the api-wp-extension plugin, we yet use regular statements, where SQL injections are possible. We should replace those with prepared statements.

"_Some of the functions in this class take an SQL statement as input. You must SQL escape all untrusted values you incorporate into the SQL query to prevent SQL injection attacks. Check the documentation to see if the function you plan to use escapes SQL for you or expects it to be pre-escaped._" [https://codex.wordpress.org/Class_Reference/wpdb

**Comment by pblanz** [comment]
After having inspected the api-wp-extension plugin again, I noticed, that we actually do not utilize user-input for the SQL-Queries, except for the timestamp within the URL. And this timestamp validated already. Thus, prepared statements aren't really necessary @Meash , are they? Thus I guess this issue can be closed.

**Comment by Meash** [comment]
Agree. We should keep this in mind though when extending our API.
I think in general, it would still be a good idea to use prepared statements everywhere at some point.
