### ISSUE TITLE
Automatic Translation also on Pages marked as "Draft"

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#315]
The Automatic Translation may also appear on pages which are currently in "draft"-mode.

**Comment by sven15** [comment]
* Is WPML working with post_status='rvy-pending' ?
* register_status for rvy-pending ?
* maybe adding the button to the revisionary edit and adding the rvy-pending status in the translation will work.

**Comment by sven15** [comment]
This is actually something we would want to have (beyond nice to have).

**Comment by sven15** [comment]
worded differently but duplicate of #354
