### ISSUE TITLE
Disable User

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#321]
Verwalter-Role should have the ability to disable a user, but only for the instance where the Verwalter is in.

Maybe it's possible with https://wordpress.org/plugins/deactivate-user-accounts/ ?

**Comment by sven15** [comment]
Is there any problem with adding the capability "delete_users" to the role Verwalter?

**Comment by Meash** [comment]
That would delete users forever, i.e. no more authorship for that user's content.

**Comment by sven15** [comment]
Is that our problem?

**Comment by Meash** [comment]
Well yes because we can't hold deleted users liable for their content.
It is easier to say "that's not our content, Mux Mastermann did that"
than
"that's not our content, that was muxm1943!"

**Comment by dkehne** [comment]
Yes I also see a problem there. Every Verwalter is responsible for the content in the instance. He has to be in control of every content<->author relation which was created at any point of time.

**Comment by sven15** [comment]
Result from last skype conference: we will just disable users with https://de.wordpress.org/plugins/disable-users/

**Comment by sven15** [comment]
Plugin available in c2461db49c2526cfc4431831ee3adf32890bc2d1. We need to remove the "delete user" links.

**Comment by sven15** [comment]
Not necessary.
