### ISSUE TITLE
Feedback für CMS und App von der Stadt Augsburg

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#322]
Hallo Daniel,
hier wie besprochen meine Beanstandungen/Wünsche:

·         Wichtig: Es sollte möglich sein, auf der App Links zu setzen, die innerhalb der App verlinkt sind und nicht auf die externe URL weiterleiten, wo man das offline ja nicht anschauen kann.

·         Die Anzeige der hinterlegten PDFs funktioniert offenbar auch nur online.

·         Ich bräuchte eine Löschberechtigung für die Dateiverwaltung.

·         Die Formatierung der Tabellen funktioniert nicht (wird nicht so angezeigt wie eingegeben bzw. verrutschen dann die Inhalte und werden dadurch unleserlich).

·         Ist es möglich, die automatische Formatierung auszuschalten? Am liebsten wäre es mir, wenn ich alles so eingeben könnte, wie es später dargestellt wird. Beispiele: Adressblöcke, Aufzählungen (da zieht es die Zeilen auseinander); Zeilenabstände zwischen Textblöcken (Fließtext + Adressblock, Adressblock + Adressblock, Fließtext + Tabelle usw.).

·         Bei den Aufzählungen fehlen z.T. die Aufzählungs-Sonderzeichen.

·         Neue Menügestaltung: Zu dem ausgewählten Oberpunkt sollten nur die zugehörigen Unterpunkte erscheinen (nicht die ganze Liste); in der Liste sollte der Oberpunkt als solcher kenntlich gemacht werden.

·         Falls technisch möglich, wäre es super, wenn wir bei den Push-Nachrichten die sprachliche/n Zielgruppe/n auswählen könnten – interessant gerade für spezielle Angebote für Afghanen o.ä.

Außerdem wird mir der Zugriff auf die „Notruf“-Seite verweigert – warum auch immer J. Und ich habe gesehen, dass bei vielen Seiten keine oder eine nur fragmentarische Übersetzung nach Persisch vorhanden ist. Wie kann das sein? Ich  gehe das aber nochmal detailliert durch.

So, ich hoffe, ich habe nichts vergessen, sonst melde ich mich nochmal.

**Comment by Meash** [comment]
> Es sollte möglich sein, auf der App Links zu setzen, die innerhalb der App verlinkt sind und nicht auf die externe URL weiterleiten, wo man das offline ja nicht anschauen kann.
siehe Integreat/app-android#155

> Die Anzeige der hinterlegten PDFs funktioniert offenbar auch nur online.
siehe Integreat/app-android#123

> Ich bräuchte eine Löschberechtigung für die Dateiverwaltung.

> Die Formatierung der Tabellen funktioniert nicht (wird nicht so angezeigt wie eingegeben bzw. verrutschen dann die Inhalte und werden dadurch unleserlich).
siehe Integreat/cms#106 und Integreat/app-android#16

> Ist es möglich, die automatische Formatierung auszuschalten? Am liebsten wäre es mir, wenn ich alles so eingeben könnte, wie es später dargestellt wird. Beispiele: Adressblöcke, Aufzählungen (da zieht es die Zeilen auseinander); Zeilenabstände zwischen Textblöcken (Fließtext + Adressblock, Adressblock + Adressblock, Fließtext + Tabelle usw.).
Wir haben keine automatische Formatierung, die App stellt die Inhalte mit einem HTML-Viewer dar. Ist da noch Klärungsbedarf?

> Bei den Aufzählungen fehlen z.T. die Aufzählungs-Sonderzeichen.
Beispiel-Seite?

> Neue Menügestaltung: Zu dem ausgewählten Oberpunkt sollten nur die zugehörigen Unterpunkte erscheinen (nicht die ganze Liste); in der Liste sollte der Oberpunkt als solcher kenntlich gemacht werden.
Geklärt mit Redesign oder? 

> Falls technisch möglich, wäre es super, wenn wir bei den Push-Nachrichten die sprachliche/n Zielgruppe/n auswählen könnten – interessant gerade für spezielle Angebote für Afghanen o.ä.
siehe Integreat/cms#330 und Integreat/app-cross_platform#43

> Außerdem wird mir der Zugriff auf die „Notruf“-Seite verweigert – warum auch immer J. Und ich habe gesehen, dass bei vielen Seiten keine oder eine nur fragmentarische Übersetzung nach Persisch vorhanden ist. Wie kann das sein? Ich gehe das aber nochmal detailliert durch.
gelöst in Integreat/cms#324
