### ISSUE TITLE
Media deletion capability for managers

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#331]
E.g. Julia wants to be able to delete media.

**Comment by sven15** [comment]
Ist nice to have? Man kann ja Dateien aus Pages entfernen. Sie "vermüllen" nur das Admin UI.

**Comment by Meash** [comment]
Ja denke es geht um das Vermüllen. Das macht schon Sinn, sonst kennt man
sich da wirklich irgendwann nicht mehr aus.

**Comment by sven15** [comment]
Currently I added the capability only for the role Verwalter.
