### ISSUE TITLE
Resource for string-translations

### ISSUE THREAD

**Issue by dlangerenken** [Integreat/cms#340]
We currently have a few hardcoded strings (and manually translated within the app) such as Settings, Disclaimer, and so on. Would be good to have a resource (city independent) /translations?language=en with [{"key":"value"}] such as "Settings" : "Einstellungen"

**Comment by sven15** [comment]
How should we solve this? One special site called "ressources" which is hidden from the web view and app?

**Comment by Meash** [comment]
We should start by thinking about where the data is input, e.g. text/csv/mo file on the server, own instance, other program etc. I think, `mo/po` files might be a good idea to start with.
From there, we can provide the data via the REST API.

**Comment by Dalanie** [comment]
any update here?

**Comment by sven15** [comment]
For now we should create static files. I don't think that creating a dynamic system is worth the effort. The app does not contain that many strings.

**Comment by mschrimpf** [comment]
If you're the one to update the code+files on every change ;)

**Comment by sven15** [comment]
We can keep the files outside of the CMS repository. Or maybe create another one? It should be quite easy to keep track of those files as long as we are not handling dozens or hundreds of translations.

**Comment by mschrimpf** [comment]
Oh I misunderstood you then - I thought you wanted to hard-code things. Files are perfectly fine, they should be easy to maintain (not as a part of the repository though imho).

**Comment by sven15** [comment]
Will be done in the xamarin app.
