### ISSUE TITLE
Update database.sql

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#346]
The local database script is out-dated.
- Plugins
- Theme
- maybe more test data

**Comment by sven15** [comment]
How about dumping the current live database, deleting all users and adding one superadmin? I could also delete all sites but "Deutschland" and "Augsburg".

**Comment by Meash** [comment]
Sounds like a plan. We might also need a second instance next to Augsburg.
Note that there are also other users that should be added, please consult
the [[Getting-started]] wiki.

**Comment by sven15** [comment]
someone could test the new dump. If accepted we can deploy it to the test system (#347). But we need to save all data from the test system first, because the click guide content is being developed in it.

**Comment by Meash** [comment]
Refine "someone" or no one will :p you can also do so in a pull request.

**Comment by sven15** [comment]
someone as in anybody who is reading this? ;-)
Login user: superuser, password: asdf

**Comment by Meash** [comment]
I've got the "I'm on vacation" card sorry :D

**Comment by sven15** [comment]
anyway it's available in the branch https://github.com/Integreat/cms/tree/database

**Comment by mschrimpf** [comment]
Make a pull request to merge it into `develop` that closes this issue.
