### ISSUE TITLE
Deploy database.sql to test system

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#347]
Our `wordpress_test` is a mixture of live- and test-data right now.
Deploy the `database.sql` script but change database logins.
This should be done after #346.

**Comment by sven15** [comment]
Do not deploy new database without talking to KDVZ first. They are developing the click guide / manual in the test system.

**Comment by sven15** [comment]
I'm not sure anymore if we really want to do this. Let's just merge the database branch into develop and not delete all the data we've got in the testing system.

**Comment by Meash** [comment]
arguments against it? it is supposed to be just testing data afterall.

**Comment by sven15** [comment]
We got several sites in there already and everybody who needs it got a login. We would just get the current Augsburg pages in the system by replacing the database content. The database.sql is more important for setting up a test system locally.

**Comment by Meash** [comment]
My biggest argument for deploying it to the test system as well is that we don't have to setup new users with a login, i.e. everyone can login right away. Obviously, we need to restrict access and keep the logins in the "internal circle" but I think, this saves us future maintenance.

**Comment by sven15** [comment]
Okay, let's wait for response from KDVZ and deploy it afterwards.
