### ISSUE TITLE
CuCo in Köln Instanz einbetten

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#349]
Die Inhalte von cuco.cologne sollen auch in der App für Köln abrufbar sein. Wie viel Aufwand ist das, wie ist der Zeitplan für die Umsetzung?

Sollten wir diskutieren. Sven hat bereits entsprechende Telefonate geführt. Schaffen wir das noch im März? @sven15 ?

**Comment by sven15** [comment]
Ja schaffen wir prinzipiell. Ich gehe davon aus, dass Köln damit nicht nur Kalender hat, sondern auch andere Inhalte?

**Comment by Meash** [comment]
I am re-labelling this as `prio:low` due to the discussion in Integreat/orga#48: functions for all instances are more important than individual ones.

**Comment by sven15** [comment]
Not needed anymore.
