### ISSUE TITLE
Rights for automatic translation

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#354]
Which roles should be able to do automatic translation? The post status will be copied from the original page. This can possibly overwrite approved translations. That's why organisations are currently not able to use the automatic translation button.

**Comment by Meash** [comment]
I think all roles should be able to do so - if you are not authorized to `publish_pages`, you should only be able to *suggest* changes anyway. The translation is just another change and should be marked and approved as such.
It would be nice if the manager could see that the edit is an automatic translation (i.e. no other changes have been made aside from translating it automatically).

**Comment by sven15** [comment]
You're right. This needs to be implemented :-)

**Comment by FritjofK** [comment]
we just need to send a hidden variable with the translate button. same as save/publish for articles. (probably)

**Comment by svenseeberg** [comment]
Postponed until API is fixed, see #523

**Comment by svenseeberg** [comment]
We don't have automatic translations anymore (for pages at least).
