### ISSUE TITLE
Q&A for content providers

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#355]
To give our members a platform to talk with each other, we should set up a Q&A forum.

Possible software: http://meta.stackexchange.com/questions/2267/stack-exchange-clones
E.g. [Question2Answer](http://www.question2answer.org/) looks good.

**Comment by sven15** [comment]
Already exists: http://hilfe.integreat-app.de/qa

**Comment by Meash** [comment]
True that.
Implemented by Sven
