### ISSUE TITLE
Activate tags and enhance API

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#361]
Provide categories for pages in order to solve the "Landkreisproblem". Categories can be used to assign pages to cities or districts.
http://www.wpbeginner.com/plugins/how-to-add-categories-and-tags-for-wordpress-pages/
The categories need to be delivered via the API.

**Comment by sven15** [comment]
Add tags instead of categories, commited with 3c051a2f7a3b46d2aa7da6740d40e37bc649d0b2

**Comment by sven15** [comment]
Gemeinden / Stadtteile will be transparently delivered as independent cities to the app. Problem with WebView???? @sascha11110

**Comment by FritjofK** [comment]
Do you think it is possible to complete this until next Conference in Q2?

**Comment by sven15** [comment]
Yes

**Comment by sven15** [comment]
Landkreiskonzept is defined solved with content loader
