### ISSUE TITLE
Automatic plugin activation does not work on live deploy

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#368]
The plugins were not automatically activated by the [plugin activation script](https://github.com/Integreat/cms/blob/develop/wp-activate-plugins.sh) after merging #362.
This functionality is especially important when new plugins are deployed or when new people set up their development environment.

**Comment by FritjofK** [comment]
Is that problem still a concern?

**Comment by sven15** [comment]
For any update to the master branch in the last 1,5 years I had to manually update the server due to directly deployed hotfixes. And it is better that an admin is doing that to prevent or directly catch larger issues. Maybe we can kill automatic deployment and close this issue? @mschrimpf ?

**Comment by mschrimpf** [comment]
> And it is better that an admin is doing that to prevent or directly catch larger issues

I disagree with this, I would argue that *automation > manual*. People always forget things and make errors. 

Direct updates to the server should not be necessary anyway since any `master` branch update is pulled automatically, this issue is only about the activation of plugins. I think they are necessary to avoid errors but I agree that they're not a top priority.

**Comment by sven15** [comment]
List of plugins needs an update as well. We we sort of automate it? @mschrimpf 
Activate all plugins that are available and include a blacklist instead of a whitelist?

**Comment by sven15** [comment]
Fixed. (most likely)
