### ISSUE TITLE
External Content Loader

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#375]
Description of ig-content-loader-base

The content loader base plugin provides an API for loading external content, interacting with users and delivering the content.
When editing a page, the user sees a new meta box called "Fremdinhalte einfügen" and can select sources manged by extension plugins (e.g. ig-content-loader-sprungbrett -> Sprungbrett Praktika, ig-content-loader-instance -> Seite aus anderer Instanz). When a source is selected, the base plugin saves the source plugin in the postmeta.

For updating the content, a URL is provided to be called by a cronjob (host/wordpress/content-loader/update). The content loader looks into the postmeta of all instances and executes a do_action('cl_update_content',$post_parent_id,$content_loader_extension_name). Extensions hooking into this action must check, if they need to act on this information. The extions can then call a cl_save_content function to store the additional text/html. It will be saved as a child to the parent post. The wp_posts entry will be updated everytime an extension saves content for the same parent id. The update (instead of new children posts) is necessary to prevent incessant growth of the wp_posts due to regular update calls.

The base plugin hooks into the_post and adds the content-loader child to the post.

**Comment by mschrimpf** [comment]
Can you describe what exactly this is supposed to do / what problem it is solving?

**Comment by sven15** [comment]
this is currently just a collection of options and ideas for collecting and inserting content from external sites like Sprungbrett

**Comment by sven15** [comment]
Updated description. Comments are welcome.

**Comment by mschrimpf** [comment]
Is this based on a 3rd-party-plugin or did/do we write all of this ourselves?
Also, I'd be interested in a screenshot of the checkbox within a page.

**Comment by julianorth** [comment]
both plugins were written  by sven and me without any 3rd pt contents.

**Comment by sven15** [comment]
Not really an "issue"

**Comment by mschrimpf** [comment]
We also manage feature requests in the issue tracker (see label `area:Functional`), so if that is the case please reopen.
