### ISSUE TITLE
Warning when changing page language

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#381]
There should be a warning when an user tries to change the language of a page.

**Comment by mschrimpf** [comment]
Depending on what it easier, we could also just hide this function alltogether. Both options are good, just go with whatever is easiest.

**Comment by sven15** [comment]
Why again did we want to do this? I don't remember any report where a user accidentally changed the language and was not able to find his way back.

**Comment by mschrimpf** [comment]
@sven15 There was one instance where we had to manually fix the language of all pages because someone didn't realize they were in another language.
