### ISSUE TITLE
HighRes flags are not scaled in WPML

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#382]
In some WPML pages our high res flags are not scaled down and displayed in full resolution.
![problem2](https://cloud.githubusercontent.com/assets/15197000/16069591/e7be228e-32cf-11e6-94cd-85776f28e38f.png)

**Comment by mschrimpf** [comment]
related to #197

**Comment by sven15** [comment]
We need to keep the original WPML flags and serve our own flags to the webview and app.

**Comment by FritjofK** [comment]
Will be solved with new design in app and later web view

**Comment by mschrimpf** [comment]
This is probably not needed more after the design decisions from I7K right?
@BerndNK Do you still need the flags in the app?

**Comment by BerndNK** [comment]
Nope. Flags are not needed anymore.
