### ISSUE TITLE
Move Hilfe-Page (Q&A + documents) into CMS

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#398]
Could we implement something like an "Open in a new Tab" Button for hilfe.integreat-app.de ~~and web.integreat-app.de~~ inside the CMS (menu)? 

This is a desirable feature of Neuss.

EDIT ms: Only the hilfe-button is needed.

**Comment by mschrimpf** [comment]
I think there is already a link to web.integreat-app.de if you click on the instance name.
Do you think we need to make that one more obvious?

**Comment by dkehne** [comment]
Oh you're right. I guess we just have to say that in our presentations....
The Help-Button would still be useful if we implement it.

**Comment by FritjofK** [comment]
Have a look at https://github.com/Integreat/orga/issues/136

**Comment by FritjofK** [comment]
Maybe also integrate the chat function when hilfe.integreat-app.de is moved to backend

**Comment by sven15** [comment]
I'm still thinking we should connect to a powerful chat like rocket chat or slack. Ideas?
