### ISSUE TITLE
MobilePreview automatisch mit App-Style updaten

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#40]
Git Hook, um bei Änderungen der JS/CSS in der App die JS/CSS in der MobilePreview upzudaten

**Comment by sven15** [comment]
Use wpautop() for preview.

**Comment by sven15** [comment]
Currently a JS script pulls the content from the text box. That does not work with wpautop(). We need to rewrite this plugin to fetch the content via an PHP API which actually can use wpautop().

**Comment by svenseeberg** [comment]
Completed with PR #534
