### ISSUE TITLE
CL Base not hooking to REST API page content delivery

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#402]
Currently the Content Loader Base is not hooked into the REST API. Therefore additions to pages are only shown in the webview but not in the app.

**Comment by mschrimpf** [comment]
Are the pages updated on every view and not stored in our own database? The REST API should grab all `wp_posts` where `post_type='page'` I think.

**Comment by sven15** [comment]
The content loader plugin adds HTML code to the beginning or end of the post_content when the post is delivered by the_post()

**Comment by sven15** [comment]
fixed
