### ISSUE TITLE
Content Loader attachment not triggering new modified timestamp

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#421]
When the content loader base attaches HTML code to a page, the timestamp of the page is not changed. The API is therefore not delivering a new version of the page.

**Comment by kummerer94** [comment]
Content-Loader:
Attaches content to a page. When the content loader base changes this content, the date of the parent post is not changed thus prompting the API to deliver a "wrong" date. (Not the date of the changed content.)

Solution: Changing the date of the parent post in the content loader.

**Comment by sven15** [comment]
Solved in bugfix/issue#421

**Comment by sven15** [comment]
Problem does not exist?! O_o
API currently does deliver after CL has updated post.

**Comment by sven15** [comment]
.... of course it does exist!
