### ISSUE TITLE
Fix activation / deactivation bug in click guide

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#424]
![bug-click-guide-status](https://cloud.githubusercontent.com/assets/15168372/19574379/4f03fd30-970a-11e6-9f97-047362d35d49.jpg)
The value of the global activation/deactivation checkbox in the network settings of click guide is not saved.

Maybe there is a problem with the update_site_option function in wp-content\plugins\ig-click-guide\options\action\saveWelcomeMessage.php

**Comment by svenseeberg** [comment]
Click guide has been thrown out.
