### ISSUE TITLE
The External-Content-Plugin is not available in English/Mutlilingual

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#425]
The External Content Plugin (see Screenshot) is not availabe in English. It would be nice to have it at least in this language because everything else is translated.

![unbenannt](https://cloud.githubusercontent.com/assets/4182469/20091806/062d68f0-a595-11e6-9fea-b16ef200d002.PNG)

**Comment by sven15** [comment]
Currently just a nice to have, because all admins speak german.

**Comment by sven15** [comment]
Could become important very quickly if international partners join Integreat.
