### ISSUE TITLE
Adding users to an instance (network site) is not possible via network settings

### ISSUE THREAD

**Issue by sascha11110** [Integreat/cms#426]
If one tries to add an user to a network site via "Netwerkverwaltung" > "websites" error message "Ungültige Website-ID." appears.

**Comment by dkehne** [comment]
The same error comes when adding a new instance or deleting an instance. If you do the same without cache in "private mode" e.g. in mozilla, it all works. so it seems to be a cache problem.

**Comment by sven15** [comment]
Never had this problem. Can someone confirm that this still persists? Otherwise please close this issue.

**Comment by sven15** [comment]
Confirmed. This is a core functionality. Should be fixed upstream ....
`host/wordpress/wp-admin/network/site-users.php?action=adduser&lang=de&redirectlang=1`

**Comment by sven15** [comment]
https://premium.wpmudev.org/forums/topic/error-when-trying-to-add-user-to-site

**Comment by benginoe** [comment]
I take care of it.

**Comment by sven15** [comment]
This is probably directly connected to #494 #495 and also to #496

**Comment by sven15** [comment]
Solved together with #494
