### ISSUE TITLE
External Content (or content from other instance) should be visible in CMS

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#427]
Currently it's misleading that the content loader (content load from other instances) is visible in the app but not in the CMS. Can we maybe insert it as "greyed out" text or is there an other suggestion to make it more comfortabel for the user?

**Comment by sven15** [comment]
Should be in both. needs to be investigated.

**Comment by sven15** [comment]
Easy fix -> upgraded to high prio

**Comment by sven15** [comment]
It's working - false report.
