### ISSUE TITLE
DDoS Protection

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#428]
Wir sind derzeit ohne großes technisches Know-How mit einem 56K Modem DDoS-bar.
Halte ich persönlich für unwahrscheinlich - was denkt ihr?

**Comment by kummerer94** [comment]
Wenig Gefahr, da niemand sich einen großen Vorteil hieraus versprechen dürfte.

Ansonsten: https://projectshield.withgoogle.com

**Comment by sven15** [comment]
Besides using something like cloudflare there is not much we can do.

**Comment by svenseeberg** [comment]
Moved to tech Trello board.
