### ISSUE TITLE
Performance Profiling

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#429]
Analyse how well we can handle multiple concurrent accesses and where our performance bottlenecks are.
This includes the following access points:
* API access
* WordPress Backend Edits
* Webview access

Check out https://codex.wordpress.org/Testing_WordPress_Performance.
Tools like [WP MySQL Profiler](https://wordpress.org/plugins/wp-mysql-profiler/), [Query Monitor](https://wordpress.org/plugins/query-monitor/) and [P3 plugin](https://wordpress.org/plugins/p3-profiler/) might be useful here.

Ideally, the results will tell us:
* how many concurrent accesses on each access point we can handle at the moment
* whether the bottleneck is PHP or MySQL
* where exactly most of the computations happen (which PHP function / which MySQL table)

**Comment by svenseeberg** [comment]
Moved to Tech Trello board.
