### ISSUE TITLE
Icons für Pages eintragen

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#43]
Bei einer Page kann man in der rechten Sidebar unten ein Beitragsbild festlegen, welches dann als Icon in der App angezeigt wird.

Zumindest für die oberste Ebene sollte das gemacht werden.

**Comment by dkehne** [comment]
Wir behalten die aktuellen Icons und crediten den Autor im Impressum der App. Ich kümmere mich drum

**Comment by Meash** [comment]
Wie ist der Stand @dkehne ?

**Comment by dkehne** [comment]
Wir nehmen die aktuellen Icons und crediten im Impressum. Dazu steht schon was in Issue 93 von der App (https://github.com/Integreat/app/issues/93).

Geht das schon das Icons nur quasi in deutsch eingefügt werden müssen und in allen anderen Sprachen vorhanden sind?

**Comment by Meash** [comment]
Theoretisch ja, das WPML Plugin dafür ist aktiviert. @dkehne Prüf das bitte mal noch, bei ein paar Seiten sind in den Sprachen außer Deutsch keine Icons. Evtl muss man im Deutschen nochmal speichern und den Haken setzen, dass das übernommen wird.

**Comment by dkehne** [comment]
Alles klar, ich prüfe hier.

**Comment by dkehne** [comment]
Okay funktioniert nicht. Haben neu gespeichert und sogar app-seitig Cache gelöscht. Geht nicht

**Comment by Meash** [comment]
Auch nicht wenn ihr beim speichern in deutsch "hochgeladene Medien in
Übersetzungen duplizieren" anhakt?
Am 25.11.2015 11:17 schrieb "Daniel Kehne" <notifications@github.com>:

**Comment by dkehne** [comment]
Nach Cache leeren funktionierts.

**Comment by Meash** [comment]
Alternativ zu Cache reload gibt's auch einen force reload indem man in der
App von oben nach unten swiped

**Comment by Meash** [comment]
Fertig? dann bitte closen

**Comment by dkehne** [comment]
Nicht ganz. Bei Auto-Translations wird das Logo nicht übernommen. Ich kann den Haken zwar setzen, nach drücken des Aktualisieren-Knopfs ist der Haken aber wieder raus und Beitragsbild wird auch nicht übernommen.

![unbenannt](https://cloud.githubusercontent.com/assets/4182469/11716437/2e36db26-9f4a-11e5-9da7-8c43c7e4b9b2.JPG)

**Comment by Meash** [comment]
see #260
