### ISSUE TITLE
Link from WebView to App

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#430]
Currently we have a lot of users on our web view coming from e.g. Google. We should inform them also that Integreat is available as an app. At this moment there is now link or hint to our app, if someone is only using our WebApp. 

Any ideas how to solve that?

**Comment by mschrimpf** [comment]
What others do:
1. subtle reference to the app, e.g. a link in the top right corner
2. if user uses mobile device, ask if he wants to use the app before loading the site

**Comment by dkehne** [comment]
Maybe like this? :D https://ankommenapp.de/asyl-ausbildung-arbeit/

**Comment by sven15** [comment]
@sascha11110 could you add this?

**Comment by svenseeberg** [comment]
Switched to WebApp. Not an issue for cms anymore.
