### ISSUE TITLE
Media Structure

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#433]
There is currently no structure or tagging for the media. This was one of the main critique points from our user survey.
It would be great if we could make it easy for users and ourselves to find media (icons, images etc)

**Comment by sven15** [comment]
https://codecanyon.net/item/wordpress-real-media-library-media-categories-folders/13155134

**Comment by sven15** [comment]
There is currently no easy way to get this. Do we REALLY REALLY REALLY need this functionality? Otherwise please close this issue.

**Comment by mschrimpf** [comment]
@dkehne mentioned this was very frustrating for some users. I think it was also one of the main criticisms during our evaluation.

**Comment by dkehne** [comment]
Yes, but as from our discussion today we will only provide Icons for the 1st content layer. So this is all in all 28 icons. If we are all of the same opinion tomorrow - we could close this issue.

**Comment by sven15** [comment]
in consultation with @dkehne deemed unnecessary
