### ISSUE TITLE
Automatically fix plugin updates

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#435]
When e.g. WPML is updated, we need to fix the flag resources because the update process overrides them.
For a complete list of post-update tasks, see: https://github.com/Integreat/cms/wiki/Updating-Wordpress-and-Plugins.

This could be solved automatically by implementing a post-update hook: http://stackoverflow.com/a/24202466/2225200
This would make the update process much easier and save us from potential user errors.

**Comment by sven15** [comment]
This will most likely only concern the tree view plugin in the future. There we need to replace one line to show open revisions from revisionary. We dont need the high res flags anymore because of the new app design.
