### ISSUE TITLE
Careers4Refugees links to API

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#440]
The app needs a link to the Careers4Refugees API for each city.

**Comment by sven15** [comment]
Do we have to manually set the URLs @dkehne ? Can be provided by new ig-extras plugin.

**Comment by dkehne** [comment]
I guess we have to set them manually. We could also suggest careers4refugees to define a name-scheme to generate them in our source code - don't know which version might be more robust.

**Comment by sven15** [comment]
As we cannot anticipate what the cities and counties want, we cannot really know in advance. I think we need to manually set the URLs.

**Comment by sven15** [comment]
Closed with 892999f83979e21c15c27615bcedd2162bd25d60
