### ISSUE TITLE
Content Actualization

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms#450]
Due to changes in the law or localizations our content might become outdatet, especially if an instance clones the content from an existing one. Even if the primary content provider updates, the content of the clone will still be the same. 
A Newspaper regarding changes or an interactive Content-Management do the trick.

Feedback from customer:

Bei der Recherche nach besseren Icons für Beratung ist mir aufgefallen, dass ihr immer noch von der Büma sprecht. Diese gibt es aber schon seit gut einem halben Jahr nicht mehr. Freising und andere haben die Vorlage von euch übernommen. Es ist echt wichtig, das rauszunehmen da die Info wirklich veraltet ist. Auch marketingtechnisch (Aktualität der App und so) ist es problematisch, wenn man sich die Apps ansieht und im Content Fehlinformationen sind... Eine Bitte aus Usersicht wäre im Falle von solchen Gesetzesänderungen eine Aktualisierung des Templates und die Info in Form eines Newsletters, dass jeder dies in der App verändert. Vielleicht baut ihr ja auch mal ein interaktives Contentmanagement, wo jeder Integreatnutzer/Admin Aktualisierungen eintragen kann und man nicht immer über euch und Mail darüber redet. Falls es das schon gibt, Asche über mein Haupt  - hab ich noch nicht gesehen.

**Comment by FritjofK** [comment]
I am thinking about a Newsletter containing content for the app that we send to the cities. They should do the work because then they also check if other things might have changed. (Maybe offer to do it for them when they have a service agreement)

**Comment by sven15** [comment]
This is definitely something the content providers have to take care of. Unless there is a technical solution to this problem we should close this bug. Actually there is one: content loader.

**Comment by sven15** [comment]
This is not an CMS issue. Created orga issue.
