### ISSUE TITLE
Permission "Delete User" should be in the role "Verwalter"

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#451]
Please add the permission to remove users from a CMS to the role of the "Verwalter". Thought that would be already in, but it isn't.

**Comment by mschrimpf** [comment]
I think the reasoning here was that a user might be in several instances - probably not relevant.

**Comment by dkehne** [comment]
I personally can delete, but "Verwalter" does not. Even if a user is in serveral instances, it can be deleted. In this case it will be only removed from the specific instance without being fully deleted. Tested it with my own user. Is it hard to grant the specific permission to "Verwalter"-Role or is it already in?
