### ISSUE TITLE
Set instance color, icon, cover image

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#48]
The manager of the instance should be able to change the instance's appearance.

The color is currently hardcoded.
The icon and cover image settings can currently only be changed in the site frontend customization. (Website-Information > Website-Icon, Header-Image).

Also see #178

**Comment by Dalanie** [comment]
!Important

**Comment by sven15** [comment]
This becomes obsolete with the new design style?

**Comment by Meash** [comment]
No we are still the ones to input all this data.

**Comment by sven15** [comment]
Not important, only required if a customer pays for the development.

**Comment by Meash** [comment]
This creates work for us (specifically the super admins). Enabling the managers to do this makes life easier for us.
Right now, we have to go to the site's webview, customize it and adjust the site icon and cover image in two separate menu points.

**Comment by sven15** [comment]
I think this is not covered by our approach to provide the same UX everywhere.
