### ISSUE TITLE
Mirrored Content does not disappear when chosen

### ISSUE THREAD

**Issue by FritjofK** [Integreat/cms#515]
In "Landkreis Heidenheim" content from other instances have been taken from other instances on the following page: 

Arbeit und Bildung>Berufsausbildung>Anerkennung von Zeugnissen 

On "Anerkennung von Zeugnissen" content from Augsburg had been inserted after the text and it does not disapper once "Bitte auswählen (nichts auswählen)" is chosen and page is updated.

**Comment by sven15** [comment]
@FritjofK are you talking about the website or app?
