### ISSUE TITLE
Bei Seiten standardmäßig die CMS TPV anzeigen

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#52]
Im Seiten-Menü soll standardmäßig die "Baumstruktur" des Plugins `CMS Tree Page View` (TPV) angezeigt werden.
"Alle Seiten" soll weiterhin als Auswahlmöglichkeit bestehen bleiben.

![pages](https://cloud.githubusercontent.com/assets/5308236/10305522/d93d3a04-6c20-11e5-80f6-9a238cec7c72.PNG)

Beim Klick auf "Seiten" soll man also direkt in der Baumstruktur landen und das Untermenü "Alle Seiten" mit der "Baumstruktur" vertauscht werden.

Verfeinerung von #37

**Comment by dwsoto** [comment]
Würde ich noch nicht schließen - beim Löschen wird beispielsweise aktuell noch auf die Standardseitenansicht weitergeleitet. Wir hatten uns darauf geeinigt, dass wir noch #130 umsetzen und dann die Standardseitenansicht ganz rausschmeißen können, richtig?

**Comment by Meash** [comment]
Ja richtig.
Hätte es bei einzelnen Issues belassen, oder gibt es gar nicht für alles
ein Issue?
