### ISSUE TITLE
Automatic Translation API changed

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#523]
Bing changed the API:

Fehler beim automatischen Uebersetzen: Fehler bei der automatischen Uebersetzung der Inhalte nach de: Method: Translate(), Message: Invalid authentication token. Microsoft DataMarket is retired. Please subscribe to Microsoft Translator, in the Cognitive Services section at https://portal.azure.com. Please visit https://cognitive.uservoice.com/knowledgebase/articles/1128340-announcements-action-required-before-april-30-20 to find detailed instructions., message id=0650.V2_Rest.Translate.D41A270

**Comment by Ponitac** [comment]
Do we have a required Azure-Account?
