### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by thimmy687** [Integreat/cms#532]
![screenshot_2017-06-15-22-04-20](https://user-images.githubusercontent.com/7715216/27199587-d9c865d8-5216-11e7-8c03-32d42e9ace5c.png)

Please check the links on this page 
-> Refugee Law Clinic Regensburg

**Comment by svenseeberg** [comment]
The link is "rlc-regensburg.de". Can the app be enabled to handle links without http(s):// at the beginning? @thimmy687

**Comment by thimmy687** [comment]
Fix on app side [here](https://github.com/Integreat/app-cross_platform/pull/183)
