### ISSUE TITLE
Wrong name displayed in editor after translation update via TM

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#535]
After finishing a translation entry via translation management (TM) the name of the creator of the artictle is mentioned as the "last editor". 

In the revision history everything is displayed okay. Is the error caused by a standard plugin or does it come from our code?

![screen_regensburg](https://user-images.githubusercontent.com/4182469/27548158-65a450b0-5a98-11e7-8aaa-74a77d2cd942.PNG)

**Comment by svenseeberg** [comment]
I'm pretty sure that we're not messing with the code there.

**Comment by Ponitac** [comment]
This seems to be eleminated in the next Plugin Update.

**Comment by svenseeberg** [comment]
@dkehne does this still happen?

**Comment by dkehne** [comment]
looks perfect.
