### ISSUE TITLE
Eingefügte Bilder immer auf width-Tag 100%

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#54]
Wenn so eingestellt, dann wird es auch in der App sauber dargestellt. Aktuell wird beim Bilder einfügen die hardgecodete Pixelsize genommen.

**Comment by sven15** [comment]
Scaling in the webview is not an issue right now and this is the wrong place vor app issues. Can we close this issue?
(And as far as I can tell it's not an issue at all right now.)

**Comment by mschrimpf** [comment]
Agree.
