### ISSUE TITLE
Create upstream patch for Author Chat 

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#540]
Commit our Author Chat changes to upstream:
* Multisite capability
* Nicer UI

**Comment by svenseeberg** [comment]
@Ponitac ist the branch Integreat/cms/tree/customized_author_char the current development?

**Comment by Ponitac** [comment]
Yes it is. Multisite is enabled, but desired UI options are not implemented
yet

Am 22.07.2017 5:46 nachm. schrieb "Sven Seeberg" <notifications@github.com>:

**Comment by svenseeberg** [comment]
plugin is not used. discuss removal on I9K.
