### ISSUE TITLE
No WPML-Support for recurrent Events

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms#586]
At local repo, the possibilty to register recurrence Events is visible and possible, but at live-system the opportunity is denied.

**Comment by svenseeberg** [comment]
which version of EM and WPML are you using locally?

**Comment by Ponitac** [comment]
EM: Version 5.7.3 and WPML: Version 2.2.2
But should be the same as on the master

**Comment by svenseeberg** [comment]
-> It should be a configuration option or another plugin is breaking it?

**Comment by Ponitac** [comment]
Problem solved! WPML Settings aren't supporting recurrence Events by default.
![grafik](https://user-images.githubusercontent.com/15608678/32723717-cdded79c-c86e-11e7-8be1-1661cc71fe10.png)

![grafik](https://user-images.githubusercontent.com/15608678/32723582-4ae05c1c-c86e-11e7-9457-4d0804ebe36c.png)
To enable it, one should use the WPML-Settings to fix it. But notice, that it is only possible for one instance, so maybe we should set the value directly in the database?
