### ISSUE TITLE
PDF generation not working correctly in Arabic and Farsi

### ISSUE THREAD

**Issue by Schedulaar** [Integreat/cms#587]
The webapp requests `https://cms.integreat-app.de/:location/wp-admin/admin-ajax.php` with some parameters (can be seen in https://github.com/Integreat/integreat-webapp/blob/master/src/components/Content/PDFButton.js), but the generated pdf in ar only contains question marks, like in https://web.integreat-app.de/augsburg/ar/%D8%AA%D8%B9%D9%84%D9%85-%D8%A7%D9%84%D8%A3%D9%84%D9%85%D8%A7%D9%86%D9%8A%D8%A9-%D9%81%D9%8A-%D8%A3%D9%88%D8%AC%D8%B3%D8%A8%D8%B1%D8%AC/deutsche-sprache. Probably due to wrong fonts(?).
// Note: There's also a font-parameter where the webapp only sends an empty string to the backend, should we put sth there?

**Comment by svenseeberg** [comment]
https://github.com/Integreat/cms/tree/feature/mpdf needs testing

**Comment by svenseeberg** [comment]
I cannot reproduce this issue. The Farsi fonts are working for me. @Schedulaar is the attached pdf displaying correctly for you?
![screenshot from 2018-02-25 11-05-48](https://user-images.githubusercontent.com/15197000/36640283-e36600c8-1a1b-11e8-9c50-c5de5b4c04f6.png)
![screenshot from 2018-02-25 11-06-33](https://user-images.githubusercontent.com/15197000/36640289-f909e8e0-1a1b-11e8-9668-ed95e3eaf27e.png)
[4648_file.pdf](https://github.com/Integreat/cms/files/1755876/4648_file.pdf)

**Comment by timoludwig** [comment]
New branch, new luck: https://github.com/Integreat/cms/tree/bugfix/ig-mpdf-2 needs testing
