### ISSUE TITLE
PageContent Metadata

### ISSUE THREAD

**Issue by thimmy687** [Integreat/cms#589]
The page permalink should be on top of each page so that the user easily can identify the current page in the App

**Comment by thimmy687** [comment]
Ich würde gern meine offene Anfrage um die tags:

<meta name="viewport" content="width=device-width">
<meta name="format-detection" content="telephone=no">

erweitern.

**Comment by Simple-codinger** [comment]
Hier die Tags: 
`<!doctype html><html><head><meta name='viewport' content='width=device-width'><meta name='format-detection' content='telephone=no'></head><body>"+pageVm.Content+"</body></html>`

**Comment by svenseeberg** [comment]
Should this be a web app issue?
