### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#594]
Analyse Sphinx Search, Elastic Search, Google API, DuckDuckGo API for better search results.

**Comment by benginoe** [comment]
Sphinx Wordpress Plugin: https://de.wordpress.org/plugins/wordpress-sphinx-plugin/

Elastic Search Wordpress: https://de.wordpress.org/plugins/elasticpress/ || https://de.wordpress.org/plugins/fantastic-elasticsearch/

Duckduckgo: https://fastwp.de/8709/
Google: costs if more then 100 requests per day are used -> out.

Sphinx: http://sphinxsearch.com/
ElasticSearch: https://www.elastic.co/de/

Remind ressources of hardware.

**Comment by svenseeberg** [comment]
I don't think that we need a web based search engine. It's more about being able to search within the app. For online search I would trust the existing search engines.

**Comment by benginoe** [comment]
I think we need a better search-engine, actually we do only a string-match in the webapp, we have to discuss and look up how we can solve this problem i think sphinx or elastic search will be the best choice, with a higher infrastracture afford but also with a good result. 

In talk with @maxammann a solution with existing wordpress plugins will be the easiest way to take care of the problem.
