### ISSUE TITLE
Cookie-Error when Logging in for the first time via xxx.integreat-app.de

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#600]
There is always a cookie error at the first attempt to login when using the url whatever.integreat-app.de
It works with https://cms.integreat-app.de/wp-login.php directy.

....and no! The solution isn't to forbid the first URL 👯‍♂️ 

![cookiues](https://user-images.githubusercontent.com/4182469/32963492-6ff1aac8-cbd0-11e7-8918-96d6bce07070.PNG)

**Comment by svenseeberg** [comment]
Works for me :-P

**Comment by dkehne** [comment]
Is working since December. So issue can be closed?!

**Comment by svenseeberg** [comment]
It is possible that the Wordpress update fixed this issue. Reopen it if necessary.
