### ISSUE TITLE
Validate content

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#601]
Try to develope plugin/script which detects and maybe cleans directly pages with 

- Clean up HTML
  -  empty html tags (e.g. `<p></p>`) [clean]
  - multiple whitespace [clean]
  - multiple commas in row [clean]
  - icons which are for labeling on second level of the menu not to be used in text [detect]
  - tables [detect]
- check image size

Maybe its helpful to use expressions. 
Maybe it would be nice to see how much issues on content are on one page in the tree-view or on a spereate plugin-site. Keep in mind multilanguage and that it would be better to clean only on click with a backup.

Done:
- Check for not working links

**Comment by svenseeberg** [comment]
Broken links can be considered "done".
