### ISSUE TITLE
Change "cms." to "web." in whole content

### ISSUE THREAD

**Issue by thimmy687** [Integreat/cms#613]
to avoid parsing and checking effort in the app please change all urls to "web."

It is necessary for the deeplinking feature.

**Comment by svenseeberg** [comment]
We can, of course, run a replace on our proxy server. That should do the trick until we migrate to a new server and want to run a replace script on all URLs in the database anyway. Opinions?

**Comment by Ponitac** [comment]
I guess this would do the trick without using a lot of effort

**Comment by svenseeberg** [comment]
We're already doing some replacements. The rest will be coming with our server migration. Closing this ticket.
