### ISSUE TITLE
Flags are too big in WPML because they were changed in the early days...

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#617]
@mschrimpf was in touch with this topic in the early days, because we needed bigger flags due to our app design. Now we don't need it anymore. I guess we have to replace them with the WPML standard again, so find the right directory and copy the standard flags from a fresh downloaded WPML package. Any other suggestions?

Currently it is really difficult for translators because in the editor view 5/6 of the screen is the flag and only 1/6 is editor for translations.

![unbenannt](https://user-images.githubusercontent.com/4182469/33423113-298937f8-d5b8-11e7-9360-8e8766550337.PNG)

**Comment by svenseeberg** [comment]
This will happen with the next WPML update. However, the last time i tried, the travis checks failed. Can someone please create a branch with WPML updates and find out what travis is complaining about?

**Comment by Ponitac** [comment]
Branch with update is already created locally. I will push it now to remote and let travis take a look :D

**Comment by Ponitac** [comment]
Fixed in #618
