### ISSUE TITLE
Extend API for Extras

### ISSUE THREAD

**Issue by thimmy687** [Integreat/cms#619]
Currently our API (v0/v1) has 4 different endpoints (https://integreat.github.io/cms/):
1. a list of all available sites (WP blogs)
2. a list of languages per site
3. changed pages per site and language
4. changes events per site and language

For the app we need an additional endpoint that provides all extras that should be enabled for each site (WP blog). Currently this information is embedded into the JSON containing a list of all sites (list item 1).

Suggested URI pattern for the endpoint:
 [Get("/{location}/{language}/wp-json/extensions/v0/extras/")]

Suggested JSON format:
`
{[
  {
   name: "IHK Ausbildingsbörse",
   type: "Ausbildung",
   enabled: "1|0",
   extension: [
                        url: "https:\/\/www.ihk-lehrstellenboerse.de\/joboffers\/searchTrainee.html?
                               location=86150&distance=1",
  },
  {
   name: "IHK Praktikumsbörse",
   type: "Praktikum",
   enabled: "1|0",
   extension: [
                        url: "https:\/\/www.ihk-lehrstellenboerse.de\/joboffers\/search.html?
                                 location=86150&distance=1\",
  },
  {
   name: "SerloABC",
   type: "Alphabetisierung",
   enabled: "1|0",
   extension: [
                        url: "https:\/\/www.ihk-lehrstellenboerse.de\/joboffers\/search.html?
                                 location=86150&distance=1\",
  },
]}
`

**Comment by svenseeberg** [comment]
@thimmy687 as we need to support old Apps as well: is this something we should postpone until APIv2?
