### ISSUE TITLE
Events can't be saved due to database problems

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms#625]
Some Instances mentioned, that they have problems with saving new events. Screenshots are attached.
![fehlermeldung oberer teil](https://user-images.githubusercontent.com/15608678/33725956-fd566752-db73-11e7-83fd-75f37503a1fe.JPG)
That's what I found by searching this problem: https://stackoverflow.com/questions/21824537/wordpress-events-manager-plugin-adding-new-events-not-working

**Comment by Ponitac** [comment]
I couldn't reproduce it as well, but I thought it might be a problem with the database structure of the event manager <4.0 and the new one

**Comment by Ponitac** [comment]
"new one" in such way, that some new field are added and in the VALIDATE METAL method they are somehow counting the fields

**Comment by dkehne** [comment]
A city just called me 5 min ago, she said the clicked on publish but got the error (two times on publish button). I asked her to save it as a draft (to check if this works) - and it worked. Then I asked her again to click on publish and it worked as well. 

Hopefully that helps to evalualte....

**Comment by svenseeberg** [comment]
@Ponitac this is fixed now, right? Could you please close this issue if my assumption is correct.

**Comment by Ponitac** [comment]
Yes, the Editor-Next-Plugin somehow broke one Hook the EM was using. We removes the Plugin and now everything works fine.
