### ISSUE TITLE
Warning for changed Pages

### ISSUE THREAD

**Issue by thimmy687** [Integreat/cms#627]
### Problem
The content have a lot of not working internal page links

### Wish
If the user change or disable an existing page, they should get a warning if the page is linked in the content.

**Comment by timoludwig** [comment]
I don't think there is an efficient way to implement this whish.
How about using the ["Broken Link Checker"-Plugin](https://wordpress.org/plugins/broken-link-checker/)?

**Comment by svenseeberg** [comment]
I agree with timos assessment and suggestions.

**Comment by timoludwig** [comment]
@thimmy687: I installed the plugin to the [feature/broken-link-checker-plugin](https://github.com/Integreat/cms/tree/feature/broken-link-checker-plugin) branch, so you can check it out locally and in case it fits your needs we will merge it.

**Comment by benginoe** [comment]
Hold till i have checked why links which are working are issued.

**Comment by benginoe** [comment]
Can be merged to live. Problem seems to be solved. @timoludwig

**Comment by svenseeberg** [comment]
Some details please @benginoe :-)

**Comment by benginoe** [comment]
Activation of php-curl was necessary that the plugin works properly. 
It should not activated networkwide, accountmanagers should have a look into the plugin at first to setup proper emailadress for each instance and communicate the activation or should deactivate the mails for broken links.

**Comment by timoludwig** [comment]
was solved in #674
