### ISSUE TITLE
Develop our own Client Dash plugin

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/cms#631]
Client Dash is not suitable for multisite Instances and has a quite big overhead. I will develop an own plugin with the same effects and remove client dash.

**Comment by svenseeberg** [comment]
@Ponitac can you please provide a list of desired features in the ticket description?

**Comment by svenseeberg** [comment]
https://codex.wordpress.org/Dashboard_Widgets_API#Advanced%3a_Forcing_your_widget_to_the_top
