### ISSUE TITLE
New Revision plugin

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#659]
Optional setting for a page: Publish version from YYYY-MM-DD HH:MM (maybe drop down menu). Save child ID that should be published as "publish_version" post meta for parent. If not set, publish most current.
If a user with the role "Organisation" saves a page, the meta tag "publish_version" is automatically set to last previous version.

**Comment by dkehne** [comment]
We also got Feedback from a second municipality that is in need of that function

**Comment by svenseeberg** [comment]
I'm thinking about a different approach to implementing that: Add an additional button on the Revisions page (https://premium.wpmudev.org/blog/post-revisions/). In addition to "Restore this Revision" we can have a "Publish this Revision" / "Diese Revision veröffentlichen" button. Opinions? @dkehne @FritjofK

**Comment by dkehne** [comment]
I am not sure if this is too confusing in the aspect of "which revision is really online" and where to publish it. What do you think of that?

**Comment by svenseeberg** [comment]
Yes, I share your concern. The advantage is, that the user can directly see the changes in the diff section. Whereas a drop down list in the editor probably leaves the user confused which version to choose. There could be several edits within several minutes and the list can potentially be very long. Therefore I think that just having a date in a drop down is not very good either.

**Comment by dkehne** [comment]
i just have a bunch of questions in my mind...don't know if we can answer them directly.

What version do we show in the editor? the latest (even if it's unpublished), the currently published version or does it differ related to the permissions of a user? 

and second questions: we mark a page with e.g. a blue label if there is a newer revision/version than the currently published one. How can someone delete this new version (and remove the blue label) if one does not like it?

**Comment by svenseeberg** [comment]
The editor will always display the newest version. The button is just for delivering a certain version via the API.

Reverting to an old version is always possible with Wordpress, see the link.

**Comment by svenseeberg** [comment]
Well, there is one huge blocker to this: the revision page has not that many hooks. We can provide a patch set that adds required hooks.

Alternatively, we're back to the original idea of adding a new box to the edit page, containing a drop down.

@timoludwig, @Ponitac opinions?

**Comment by svenseeberg** [comment]
See #701

**Comment by timoludwig** [comment]
was solved in #716.
