### ISSUE TITLE
Get Long/Lat for Event Manager Locations

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#664]
Resolve longitude and latitude for Event Manager locations when saving and attach as post meta.

**Comment by svenseeberg** [comment]
The Events Manager has built in longitude and latitude for each location. It is also using the Google Maps API. However, the Augsburg locations are not resolved to coordinates.

**Comment by svenseeberg** [comment]
http://wp-events-plugin.com/documentation/google-maps/api-key/

@dkehne / @FritjofK if we want to resolve coordinates for events, we simply need to activate that. Sadly, this has to be done for each individual page. This may be a good thing, because cities can agree before embedding Google Maps into their backend.

**Comment by dkehne** [comment]
page means every instance right? i guess this is a good thing, regarding the point you mention.
