### ISSUE TITLE
Übersetzung von wiederkehrenden Events

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#67]
According to https://wordpress.org/plugins/events-manager-wpml/: 
"Recurring Events can't be translated when editing the recurrence template, they must be done one by one i.e. at single event level.
Recurring events are disabled by default due to the above"

Mit Hook anpassen, sodass bei der Übersetzung alle einzelnen Events übersetzt werden.

**Comment by sven15** [comment]
will be implemented with #406 anyway
