### ISSUE TITLE
Change text of registration mail

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms#672]
Adapt the text of the registration mail so it fits our needs and sounds more formal

**Comment by timoludwig** [comment]
Let's give it a try.

**Comment by timoludwig** [comment]
But this plugin only changes the appearance of the emails. This is also a nice to have, but not what we intended... I suggest this plugin to change the actual text of the registration mail: https://wordpress.org/plugins/welcome-email-editor/

**Comment by svenseeberg** [comment]
I do not think that this plugin is a good solution. We would have to update this for each city individually. On the other hand it is quite easy to hook into the send e-mail functions and manipulate the mails. I think an acceptable solution is to hard code the mail into our own plugin.

**Comment by svenseeberg** [comment]
Another problem:

```SB Welcome Email can not function because another plugin is conflicting. Please disable other plugins until this message disappears to fix the problem.```
