### ISSUE TITLE
Remove obsolte EXTRAS settings

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#682]
We have for settings in the cms which are not needed because they were only for (testing?) purposes? 

Could we remove them?

![unbenannt](https://user-images.githubusercontent.com/4182469/37390996-2a4fb9ce-276a-11e8-9d93-70fe4dd6488f.PNG)

**Comment by svenseeberg** [comment]
We probably need a removal plugin for that. The plugin activates once and purges all old blog_options.

**Comment by timoludwig** [comment]
This is a trivial task:
https://github.com/Integreat/cms/blob/ig-delete-options/wp-content/plugins/ig-delete-options/plugin.php
