### ISSUE TITLE
Sitemap.xml generation with API-Endpoint

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#698]
We need a sitemap for better crawling and requesting crawlers to visit for a coffee in intervalls or if a new instance is published.

Should contain: sites, categroies, events with different `<priority>` (0.1 - 1.0), `<lastmod> `(YYYY-MM-DD), `<changefreq>` (always (changes each time the page is accessed), hourly, daily, weekly, monthly, yearly, never (used for archived pages)).

Instance-Sitemaps should be linked in the head-sitemap.xml, which should be refered in the robots.txt, instance-sitemaps should be placed in a subfolder.

Cralwer should be informed on the next day if new instances are published and maybe in intervalls.

**Comment by svenseeberg** [comment]
How should the priorities be created? By the cities?

**Comment by timoludwig** [comment]
I think we shouldn't add the possibility to modify the priority of single pages, as we probably won't notice a big difference in search results and it is a lot of effort to rank all pages and set the desired priority. I think we rather should derive the priority from the existing meta-tags as post-type, content-length, post-modified etc. At the moment, I ranked category-pages with 0.5, events with 0.8 and content-pages with 1.0:
https://github.com/Integreat/cms/blob/9da1c0253a434d875635eedbdada8254f7a5dfee/wp-content/plugins/ig-sitemap/IntegreatSitemap.php#L84-L92

**Comment by svenseeberg** [comment]
Okay, let's try that.

**Comment by benginoe** [comment]
We can change the priroty of the three different content-types later, if we think it has to be adjusted new. Our influence in ranking of single pages is nearly none with this attribute.

**Comment by timoludwig** [comment]
was solved in #700
