### ISSUE TITLE
Ping Crawler if new instance is published

### ISSUE THREAD

**Issue by maxammann** [Integreat/cms#706]
The sitemap.xml needs to be send to SEs.

**Comment by maxammann** [comment]
Should we also do this on a regular basis?

**Comment by svenseeberg** [comment]
See here: https://developers.google.com/webmaster-tools/search-console-api-original/v3/sitemaps/submit

We could do this with a cron job that triggers a new API end point.

**Comment by benginoe** [comment]
should be also done for the other crawlers if it isnt to much effort especially for bing. 

we dont need to do this on a regular base, normaly crawler dont come to often to your site but on a smart regular base.

**Comment by Schedulaar** [comment]
I don't have experience on that. But I think we should first check that we make the sitemap available at https://web.integreat-app.de/sitemap.xml
I think crawlers then check the sitemap.xml every few days, so I wouldn't think it's necessarily required to ping them (I don't think it results in a better SEO ranking, but I don't know the algorithms 😅 ) ...

**Comment by svenseeberg** [comment]
Okay, then there is no need for a ping. I'll close the ticket for now.
