### ISSUE TITLE
Add meta tag for a page description

### ISSUE THREAD

**Issue by maxammann** [Integreat/cms#707]
A descrption per page or per instance improves SEO. This needs to be disussed.

**Comment by maxammann** [comment]
WEBAPP issue: https://integreat.atlassian.net/browse/WEBAPP-261

**Comment by maxammann** [comment]
This has pretty high prio for us :) Last task for SEO for the WEBAPP

**Comment by svenseeberg** [comment]
@maxammann can you please provide some details here?

**Comment by svenseeberg** [comment]
I cannot work on this issue if I cannot find any information about what needs to be done :-)

**Comment by timoludwig** [comment]
If I remember it right, we wanted to provide a description for the webapp to put in the meta tag of their html header (not primarily because of seo, but because search engines show the meta description in the overview of the results).
One idea was to give the cities the opportunities to manage this description themselves, but Daniel told us that the cities probably won't care about this. So instead we should just create one general description for Integreat, translate it into all available languages and provide it to the webapp, e.g. through another api endpoint.
Optional we could add a possibility to change the description in WordPress (e.g. as part of the Integreat Settings Plugin), but the description won't change on a regular basis.

**Comment by svenseeberg** [comment]
So as a quick fix we can simply add this hard coded to the web app. It would not make any difference (besides better performance).

**Comment by maxammann** [comment]
@timoludwig I think If we add the same description on every page then it won't help us at all. 

If there won't be any human input for the descrption then we can close this I think :/

But maybe there is a wordpress description field for every post.

**Comment by benginoe** [comment]
As Timo mentioned, the consens with Daniel was to provide one general text translated into all languages of each city (same for all sites of them) with only changing the city name.

The text should be smthlike "Auf der Suche nach lokalen Informationen in Bochum? Hier findest du  mehrsprachige und aktuelle Information von deiner Stadt!" this is just an example, we could discuss this on the content-channel if nobody has a real good idea?

And it doesnt have any effect on seo.

**Comment by maxammann** [comment]
@svenseeberg @benginoe  maybe we add the meta-description only if the except is explicitly set by the cities? If the cities don't add some information it really doesn't make sense to use the meta-description.

**Comment by timoludwig** [comment]
At the moment, only posts (e.g. events) can have manual excerpts, so even if we enable excerpts for pages asap, it will take very long until a significant part of pages will have a meaningful excerpt. However, if we still wanted to add manual excerpts for pages, we would have to add the line `add_post_type_support( 'page', 'excerpt' );` somewhere in the code.

**Comment by maxammann** [comment]
@timoludwig yeah but it really makes no sense to auto generate these. Google will make a better job at this :P

**Comment by svenseeberg** [comment]
Can we please as a start hardcode a non localized string into the web app and see if this has any meaningful impact?

**Comment by maxammann** [comment]
@svenseeberg what should we use as descrption then?

**Comment by svenseeberg** [comment]
@maxammann: That is a question that needs to be asked elsewhere :-)

**Comment by svenseeberg** [comment]
@dkehne @benginoe is there a need for a generic description in Google search results? If yes, please provide a sentence.

**Comment by dkehne** [comment]
only if it's more suitable than the standard descriptions. does not make sense if any search result from Integreat has the same description. what do you think @benginoe or did i get it wrong?

**Comment by maxammann** [comment]
@dkehne we need a description which for pages like: https://web.integreat-app.de/augsburg/de

The description should include what this page is for. I'd go with a generic description for all cities.

**Comment by dkehne** [comment]
Do we need to have it in different languages? 

Suggestion:
Find local relevant content, events and possibilites to become part of your new city. Integreat helps you to connect to others and supports multiple languages.

**Comment by svenseeberg** [comment]
I would make it even shorter: ```New in your city? Find the information you need.```

**Comment by maxammann** [comment]
@dkehne @svenseeberg I'd go with the longer one. I think most of the search results use a longer description (also the automatically generated ones are longer)

So you also expect that the integreat result looks like the others.

**Comment by Schedulaar** [comment]
Maybe we should also adjust the text at least a little bit to the city we're in... So for example - description at https://web.integreat-app.de/en/augsburg:
`Find local relevant content, events and possibilites to become part of Augsburg. Integreat helps you to connect to others and supports multiple languages.`

It would also be cool, if we had that snippet translated into multiple languages, so we can adjust it accordingly - e.g. in German at https://web.integreat-app.de/de/augsburg
But I see problems with the prepositions in different languages (`in Augsburg` aber `*im* Landkreis xyz`)^^

**Comment by timoludwig** [comment]
> But I see problems with the prepositions in different languages (in Augsburg aber *im* Landkreis xyz)^^

As you get the city prefix via the APIv3, you could theoretically adjust the preposition dependent on the prefix:
- `null` -> in
- Stadt | EAE -> in der
- Landkreis | Kreis -> im

**Comment by maxammann** [comment]
Maybe let's split this one. First go with a static text and then make it dynamic.

**Comment by svenseeberg** [comment]
closed as discussed on IXIK
