### ISSUE TITLE
Add FCM sent messages overview

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms#741]
**Is your feature request related to a problem? Please describe.**
If a lot of user do have the possibility  to send Push Notifications, there should be an overview about notifications that has been sent. So when other user want to send something about the same topic, they have the possibility to see related notifications.

**Describe the solution you'd like**
Add an overview(like a simple table) to the Notifications Page. Maybe create a new table with notifications(preferred option!) or add new custom post type. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by svenseeberg** [comment]
This depends on #774

**Comment by svenseeberg** [comment]
See https://github.com/Integreat/wp-ms-firebase-cloud-messaging/tree/feature/version-2.0 and https://github.com/Integreat/cms/tree/feature/fcm-improvements

**Comment by svenseeberg** [comment]
Fixed with #784
