### ISSUE TITLE
Author Chat DB error

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#751]
**Describe the bug**
/var/log/apache2/error.log:
```WordPress-Datenbank-Fehler Table 'ig_cms.wp_author_chat_color' doesn't exist f\xc3\xbcr Abfrage SELECT tag, color FROM wp_author_chat_color where site=0 von require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/author-chat/pp-author-chat.php'), include('/plugins/author-chat/pp-process.php'), referer: https://cms.integreat-app.de/kreissegeberg/wp-admin/index.php```

**Comment by Ponitac** [comment]
Did this appeared again or was this just a single event?

**Comment by Ponitac** [comment]
I took a look into our logs and this never showed up again, so I will close this.
