### ISSUE TITLE
Enhance page tree view with mirroring information 

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#760]
**Is your feature request related to a problem? Please describe.**
Sitemanager doesnt have the possibility to see which site is mirrored and from where the content is mirrored in the overview and on the single site this should be displayed more present.

**Describe the solution you'd like**
Nice implementation would be a prominent different colour, which is explained with a legend, and the information from where the site is mirrored with titel or/and site-id, this should be clickable. 

On the mirrored site there should be also a additional information, from where the content is mirrored and that the content is mirrored.

**Describe alternatives you've considered**
None, but you are free to design as you want... but i also requested a ux assist

**Comment by svenseeberg** [comment]
@benginoe with 'site' you are probably referring to 'page'? So we're talking about the tree view plugin for pages?

An implementation is not that difficult. We're already replacing the required line in the tree view plugin. We could create a new function in ig-cms-tree-page-view-extensions that creates the required HTML code and plug it in here:
https://github.com/Integreat/cms/blob/240a6e1f0033e28fe395b84541405c1fbccd79eb/wp-content/plugins/cms-tree-page-view/functions.php#L1507

**Comment by benginoe** [comment]
yes i do mean 'page' with 'site'.
