### ISSUE TITLE
Event Form

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms#762]
Provide an APIv3 endpoint to submit events without a cms user login (probably include a captcha).

**Comment by Schedulaar** [comment]
Team webapp would suggest to add the frontend for the form as a route in our source code, sth like: 'https://integreat-app.de/augsburg/de/events/submit'.
Therefore we'd need a corresponding POST endpoint.

**Comment by svenseeberg** [comment]
Reopening this to enhance the "push content" API.
