### ISSUE TITLE
Strip past events from APIv3 reponse

### ISSUE THREAD

**Issue by Ponitac** [Integreat/cms#769]
**Is your feature request related to a problem? Please describe.**
At the moment all existent events(old and even test events) are delivered via the API and increases the 
data package.

**Describe the solution you'd like**
Filter the events before they gets send in the response.

**Comment by Ponitac** [comment]
![grafik](https://user-images.githubusercontent.com/15608678/42125465-a8c667aa-7c77-11e8-8197-6da0ef33123b.png)
As you can see, we respond with a lot of unnecessary stuff, that just gets ignored by the frontend.

**Comment by svenseeberg** [comment]
This is affecting APIv3. What is our solution here? Do not include events in the answer that are older than 1 week? And also we should correctly put them in the list of deleted items. @timoludwig can you have a look here?

**Comment by timoludwig** [comment]
Was solved in https://github.com/Integreat/cms/pull/827. I removed all events from the result with an `event_end_date` which is in the past. There were no changes needed for the APIv3-functionality, as they are in the list of deleted items automatically if past events are sent to the server in the request.
