### ISSUE TITLE
Change URL of lehrstellenradar-extra

### ISSUE THREAD

**Issue by Schedulaar** [Integreat/cms#790]
**Describe the bug**
Currently, the extras-endpoint delivers https://www.lehrstellen-radar.de/5100,0,lsrsearch.html for the lehrstellenradar-extra, because the webapp didn't support post-data so far.
Once https://github.com/Integreat/integreat-webapp/pull/188 is deployed (I will remind you), we should change this url to https://www.lehrstellen-radar.de/5100,0,lsrlist.html again.

**Comment by svenseeberg** [comment]
Let's move this to a trello card as this is not an issue for the CMS code base.
