### ISSUE TITLE
Redirect to WebApp with status code 301

### ISSUE THREAD

**Issue by Schedulaar** [Integreat/cms#800]
**Is your feature request related to a problem? Please describe.**
Currently we're redirecting with 302. Search-Engines like 301 better for permanent redirects.
https://en.wikipedia.org/wiki/HTTP_301#Search_engines

**Describe the solution you'd like**
kwt.

**Describe alternatives you've considered**
kwt.

**Additional context**
![image](https://user-images.githubusercontent.com/7025199/44658200-40b5ff00-aa43-11e8-827a-d703b406403c.png)

**Comment by svenseeberg** [comment]
See https://stackoverflow.com/questions/7324645/php-header-redirect-301-what-are-the-implications
