### ISSUE TITLE
Sitemaps producing wrong output

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#803]
There are three different routing errors:

1. Delivering old Frontend Design: 
https://web.integreat-app.de/lkansbach/ar/sitemap.xml
https://web.integreat-app.de/donau-ries/ar/sitemap.xml
https://web.integreat-app.de/luneburg/en/sitemap.xml

2. Routing to cms.integreat-app.de/$CITYNAME; which is a blanko white site
http://web.integreat-app.de/euskirchen/fa/sitemap.xml
https://web.integreat-app.de/rosenheim/fr/sitemap.xml

3. Delivering also a wrong frontend-design, probably its a basic WP-design
https://web.integreat-app.de/lkneumarkt/ar/sitemap.xml

**Comment by benginoe** [comment]
In all cases we are publishing in "web.integreat-app.de/sitemap.xml" languages of intsances which are not anymore available.
