### ISSUE TITLE
lkaugsburg is not delivered via API (or not displayed in webapp)

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#846]
I just renamed the old instance lkaugsburg to lkaugsburg-alt and archived it. Then I created a new instance with id lkaugsburg. This instance is not delivered via API or not visible in the integreat.app. 

![unbenannt](https://user-images.githubusercontent.com/4182469/47728444-a3ec2980-dc5e-11e8-9ba1-b76c51522663.PNG)

**Comment by svenseeberg** [comment]
Its in the API: 
* https://cms.integreat-app.de/lkaugsburg/de/wp-json/extensions/v0/modified_content/pages?since=2016-01-25T09%3A27%3A49%2B0000
* https://cms.integreat-app.de/lkaugsburg/de/wp-json/extensions/v3/pages

**Comment by svenseeberg** [comment]
It does not appear in https://cms.integreat-app.de/wp-json/extensions/v3/sites

**Comment by svenseeberg** [comment]
Maybe there was a PHP execution timeout during the copying process?

**Comment by dkehne** [comment]
I deleted the old instance. Now it works. Maybe some error because of the same id?!

**Comment by svenseeberg** [comment]
This happened again with Altmühlfranken.
