### ISSUE TITLE
Rename "Seite anhängen" to not confuse the user

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#847]
Our feature to mirror content is advertised as "Intelligente Inhalte (Spiegeln)", so we should rename this widget in our cms as well. Currently its name is "Seite anhängen". In this case we should also add a sentence before the radio buttons: "Wo sollen die Inhalte eingefügt werden?" with the answers "am Anfang" and "am Ende".

Stadt wählen should be renamed to "Integreat-App wählen".

![unbenannt](https://user-images.githubusercontent.com/4182469/47778291-d5b0cf00-dcf6-11e8-88b3-fbded85a0210.PNG)

**Comment by Ponitac** [comment]
Done on my local branch. Will be pushed to remote, when I have internet connection again

**Comment by Ponitac** [comment]
Fixed in #863
