### ISSUE TITLE
p-tags stripped in translations

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#862]
Translations are missing p-tags. This happens in the XLIFF translation process.

**Comment by svenseeberg** [comment]
@dkehne see previous comment.

**Comment by dkehne** [comment]
i will ask tolingo if they can try a test export / translation

**Comment by svenseeberg** [comment]
AFAICT this is solved. @klinzo ?

**Comment by klinzo** [comment]
I haven't noticed any missing p-tags in the translations, so yes, this is probably solved. @FritjofK have you noticed any missing p-tags while reviewing the translations?
