### ISSUE TITLE
Klonen der/des VM/Servers

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#87]
Klonen des Servers um schnell auch auf einem anderem System bei Ausfall der jetzigen Hostmaschine/Cloud Daten bereitstellen zu können für die User.

Konzept erstellen und weiteren Standort mit Server erörtern.

**Comment by sven15** [comment]
MySQL Server is already working in Master-Slave mode. PHP can be distributed over several VMs: https://github.com/Integreat/cms/wiki/Load-Balancing-configuration
