### ISSUE TITLE
DNS Optimierung / Anpassung an einen schnellen wechsel der Zieladressen.

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#88]
DNS Optimierung / Anpassung für einen schnellen wechsel der Zieladressen zur Gewährleistung eines Informationsflusses an Clients und der Website.

**Comment by pblanz** [comment]
Kannst du das Problem (falls immer noch gegeben) genauer Beschreiben?

**Comment by dkehne** [comment]
@benginoe was ist hier gemeint?

**Comment by sven15** [comment]
has been fixed. I think this was concerning a shorter TTL for the DNS caches?!
