### ISSUE TITLE
WPML cannot send pages to translation due to Base64-encoded fields

### ISSUE THREAD

**Issue by FritjofK** [Integreat/cms#890]
**Describe the bug**

When sending pages to translation for two pages the following error was thrown. 
Titles have been changed in the following way: 
old -> new
Bundesfreiwilligendienst -> Bundesfreiwilligendienst (BufDi)
Migrationssozialberatung -> Migrationsberatungsstellen (Migrationssozialberatung)

Then they were able to be sent to translation. 

**To Reproduce**

**Screenshots**

Error Message

![image](https://user-images.githubusercontent.com/16462172/50099317-18ceef00-021e-11e9-8330-52ef2cb40f29.png)

**Additional context**

**Comment by FritjofK** [comment]
I have got the same problem again. 

This time in Landkreis Garmisch-Partenkirchen with the site's name: Schwangerschaftsberatung: 

![image](https://user-images.githubusercontent.com/16462172/59423208-fd5e2e80-8dd1-11e9-87be-2158c1d46e20.png)

Do we have any idea what is happening here?

**Comment by FritjofK** [comment]
There is some documentation for this: 
https://wpml.org/documentation/translating-your-contents/page-builders/how-to-fix-encoding-of-fields/?utm_source=wpmlplugin&utm_campaign=content-translation&utm_medium=translation-basket&utm_term=how-to-fix-encoding-of-fields

**Comment by timoludwig** [comment]
I already tried the solution described there the last time the error occurred, but unfortunately it didn't work.
