### ISSUE TITLE
PDF API not working

### ISSUE THREAD

**Issue by Schedulaar** [Integreat/cms#895]
The PDF API doesn't work if provided with a url of a post, e.g. https://cms.integreat-app.de/augsburg/en/wp-json/ig-mpdf/v1/pdf?url=/augsburg/en/german-language

**Comment by timoludwig** [comment]
It seems that this is a bug of Wordpress Core or WPML which causes the inbuilt function `url_to_postid()` to fail if the language is not 'de'. However, if found a work-around this: If you remove the slash in the beginning of the path, everything works fine, e.g. [https://cms.integreat-app.de/augsburg/en/wp-json/ig-mpdf/v1/pdf?url=augsburg/en/german-language](https://cms.integreat-app.de/augsburg/en/wp-json/ig-mpdf/v1/pdf?url=augsburg/en/german-language).
I will provide a fix in the API as soon as possible.
