### ISSUE TITLE
"Bestehenden Benutzer hinzufügen" entfernen

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#90]
Beim Erstellen eines Benutzers ist die erste Option, einen bestehenden Benutzer aus dem Netzwerk hinzuzufügen.
Dies verwirrt und sollte entfernt werden.
Auch prüfen, ob beim WordPress Update die Änderung gewahrt wird.

**Comment by dkehne** [comment]
Sieht gut aus so!

**Comment by Meash** [comment]
Der jetzige Stand ist keine permanente Lösung - jedes WordPress-Update überschreibt diese Änderung (s.o.).

**Comment by dkehne** [comment]
Damn. @pblanz kannst du mal googlen obs da was sinnvolles gibt was uns weiterbringt?

**Comment by sven15** [comment]
We are teaching the cities that this is a feature when working with several cities, etc.
