### ISSUE TITLE
Add possibility to exclude text from translation

### ISSUE THREAD

**Issue by klinzo** [Integreat/cms#903]
Because of the attempt to allow automatic translations with DeepL, we need a possibility to exclude text from automatic translation in the editor.
Use the `translate="no"` attribute (https://www.w3schools.com/tags/att_global_translate.asp).

**Comment by svenseeberg** [comment]
We need a button in TinyMCE that toggles the `translate="no"` attribute for the current span or p tag.

**Comment by svenseeberg** [comment]
http://archive.tinymce.com/wiki.php/api4:method.tinymce.dom.DOMUtils.setAttrib
