### ISSUE TITLE
New users are not created and redirect to old webapp

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#904]
Since the end of November there is probably the problem (at least in the instance of the district of Euskirchen) that new users get an activation e-mail, but after clicking on the link a) they are redirected to the old WebApp and b) the user himself is not created.

![webapp](https://user-images.githubusercontent.com/4182469/51669939-d2f80a00-1fc5-11e9-9486-b8c3c31698b1.PNG)

This is the link from the mail: Bitte klicke auf den folgenden Link, um dein Benutzerkonto zu aktivieren:
https://cms.integreat-app.de/euskirchen/wp-activate.php?key=f523a16db5cf39d3

**Comment by timoludwig** [comment]
This should be resolved by PR #889. @svenseeberg, can you verify this and merge the PR?

**Comment by svenseeberg** [comment]
Oh right, yes. Okay. Let's merge and commit this to master.

**Comment by svenseeberg** [comment]
Fixed with 3191e9dd7ab5a088f9359a3b06ba7a29211836f4
