### ISSUE TITLE
Icon beim Login in Project-Icon ändern

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#91]
Derzeit wird beim Login das WordPress-Icon angezeigt, ändern in das Projekt-Icon.
![delete](https://cloud.githubusercontent.com/assets/5308236/10566620/0513fce6-75ed-11e5-8c06-57edff673a5e.PNG)

**Comment by Meash** [comment]
Vlt hilfreiches Plugin: [TR WP Custom Login Page](https://wordpress.org/plugins/tr-wp-custom-login-page/)

**Comment by dkehne** [comment]
@pblanz @sven15 : Pirmin oder Sven - Wäre mega mega mega, wenn jemand hier mal schnell das Quick-Win-Potential abrufen könnte. :) Logo im Drive!

**Comment by dkehne** [comment]
Maybe this can help: https://codex.wordpress.org/Customizing_the_Login_Form#Change_the_Login_Logo

**Comment by Meash** [comment]
Hier ist wichtig, dass die Änderung persistent bleibt und nicht beim nächsten WordPress-Update wieder überschrieben wird. Dafür fehlt uns allgemein noch eine Strategie, lessons learned also bitte ins Wiki.

**Comment by sascha11110** [comment]
Warum sollte eine Zeile Code in irgendeinem Plugin, das einen
entsprechenden Hook aufgreift und das Logo verändert durch ein WordPress
Update überschrieben werden?

Machen wir für so einen Kleinkram immer ein extra Plugin oder irgendeine
Art Sammel-Plugin, wo dann alles reinkommt analog zur functions.PHP?

Martin Schrimpf <notifications@github.com> schrieb am Mi., 13. Jan. 2016
11:16:

**Comment by Meash** [comment]
Ja genau das ist die Frage :D
Ich würde hoffen, dass es eine von Plug-ins und themes unabhängige
functions.php gibt.
Dort können wir dann besagten Projekt-spezifischen Kleinkram rein packen.
Am 13.01.2016 11:29 schrieb "sascha11110" <notifications@github.com>:

**Comment by sascha11110** [comment]
Wenn uns dazu beiden nichts einfällt, ist es dann nicht wahrscheinlich,
dass das Problem (zumindest bei Plugins) nicht existent ist? :D Mit
Ausnahme dass irgendwann mal eine Funktion oder ein Hook deprecated ist

Außerhalb von Plugins und Themes muss man wohl im Core rumpfuschen und das
ist hinsichtlich der Beständigkeit wohl noch schlechter

Martin Schrimpf <notifications@github.com> schrieb am Mi., 13. Jan. 2016
11:34:

**Comment by Meash** [comment]
Ja Plug-ins funktionieren, klar. Ist halt die Frage, ob wir wirklich für
alles Plug-ins nehmen wollen oder ob es nicht sowas wie eine Projekt
spezifische functions.php gibt.
Hast aber recht, Plug-ins funktionieren - und lassen sich an- und
ausschalten. Also bleiben wir erstmal dabei.

**Comment by pblanz** [comment]
Man könnte man ein Plugin verwenden, welches als Container für kleine Plugins dient. Über die entsprechende Admin-oberfläche könnte man die Sub-plugins dann ein/ausschalten.

**Comment by Meash** [comment]
resolved in #270
