### ISSUE TITLE
Recurring events in "Landau in der Pfalz" are shown twice

### ISSUE THREAD

**Issue by FritjofK** [Integreat/cms#911]
Although being created only once in CMS recurring events are shown twice.

![image](https://user-images.githubusercontent.com/16462172/51824711-532eb000-22e3-11e9-8117-264dd68decb6.png)

**Comment by svenseeberg** [comment]
![image](https://user-images.githubusercontent.com/15197000/51829802-9a6e6e00-22ee-11e9-876c-481d7398ea8a.png)

The event appears twice in the API. It seems it only appears once in the Event Manager. Therefore it is probably an API bug.

**Comment by timoludwig** [comment]
I've seen this before. This is an issue related to the configuration of wpml and events-manager. In general, this means that wpml & events-manager are working just fine, and our workaround in the API is causing double entries and should be removed. Unfortunately this behavior was not reproducible for me, so if we just remove the workaround, then the recurring events are probably not shown in other cities.
So I suggest this procedure: We search for the difference in configuration of wpml & events-manager in Landau in comparison to other cities, e.g. Herne or the test environment. If we find the cause of the behavior, in other words if we can reproduce double events in all cities, then we configure all other cities the Landau-way and remove the workaround. If we don't find the cause, we keep the workaround and filter the API result by all removing double entries in the end.
