### ISSUE TITLE
Fix imprint links

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#916]
The sitemap.xml (https://integreat.app/euskirchen/en/sitemap.xml) contains not working links to the imprint, for example https://integreat.app/euskirchen/en/disclaimer/impressum/.

The correct link is https://integreat.app/euskirchen/en/disclaimer/

**Comment by svenseeberg** [comment]
I guess we should use this issue to clean up the Impressum / Imprint / Disclaimer mess up.

First: Disclaimers are BS and not needed at all. We need an imprint (or Impressum). I would like to get rid of the word disclaimer in the URL. I would also like to get rid of the [...]/disclaimer/impressum/ end point.

As our API is in english, we should use the word "imprint" for the end point.

Opinions @maxammann @timoludwig ?

**Comment by timoludwig** [comment]
@maxammann Can you just use the path from the disclaimer endpoint? Then we could ensure that the site map and the web app use the same permalink.
@svenseebeerg I think it would be good if the path of the imprint is the word "imprint" translated into the respective language. Can we force this and disable the possibility to edit permalinks just for the post type 'disclaimer'?

**Comment by maxammann** [comment]
@timoludwig not really. We would have to do first an api request (no matter which route the user selects) and build the route tree based on that.

**Comment by timoludwig** [comment]
I'm not sure if I made myself clear, therefore I will describe my thoughts a bit more detailed:

The sitemap currently lists all pages and their permalinks in the way they are stored in the database. The url of the imprint (at least from the perspective of wordpress) is chosen by the cities. So the issue described above arises when the cities chose bad urls for their imprints.

I see two solutions here:
1. The webapp requests the imprint endpoint (currently named `/v3/disclaimer`) to retrieve the permalink of the imprint (via the url or path parameter of the response), no matter if they are good or not. This way, the cities have full control over the url and we make sure that at least the sitemap and the actual urls are identical. This solution would require no changes to the cms, but probably means some effort for the webapp to implement it.
2. We agree on static urls for the imprint and hardcode them both in the sitemap as well as in the webapp. This would be less flexible, but we have consistent and well readable urls. Additionally, we could agree on urls based on language, e.g. `/en/imprint/`, `/de/impressum`, etc. This solution would require changes to both cms and the webapp.

I personally would prefer option 2.
@maxammann @svenseeberg what do you think?
