### ISSUE TITLE
Fix timezone for events API

### ISSUE THREAD

**Issue by maxammann** [Integreat/cms#927]
**Describe the bug**
The events API does not deliver the timezone of the event. For example if you create an event in the cms which takes place in New York at 15:30 pm the API will just return 15:30 as start_time.

In the client we do not know how we should parse that string as we do not know which timezone.

As the modified_gmt is in GMT+0 the times of the events should use this aswell probably. Or use ISO 8601 with timezones: 2008-09-15T15:53:00*+05:00*

**To Reproduce**
* Create event in different timezone
* check times in api

**Comment by svenseeberg** [comment]
Is it okay to provide an extra key "timezone" in the "events" object? If we just use the database content, then it would be in the written tz format, i.e. "Europe/Berlin" or "America/New_York".
