### ISSUE TITLE
Locations "Titelbild" Platzhalter

### ISSUE THREAD

**Issue by Dalanie** [Integreat/cms#93]
Derzeit ist das Titelbild in der Navigation hardgecoded - kann es von mir aus auch erstmal bleiben, aber ich hätte trotzdem schonmal gerne nen Platzhalter im JSON, sodass ich, sofern das Bild gesetzt wird, einfach dieses nehmen kann, an Stelle des aktuellen Hardgecodeden.

Also bei Location bitte irgendwas in Richtung "panoramaPicture"="" oder null mitliefern! Merci.

**Comment by Meash** [comment]
solved in #178
