### ISSUE TITLE
PDF creation works not correctly with Arabic&Icons

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#933]
I have found a bug in the creation/generation of PDF files. The icons i embedded, are on the other site in the PDF. I have attached two screenshots how it looks like in the webapp (that's how it should look like) and how it's displayed in the PDF (incorrectly)

WebApp:
![shouldlooklike](https://user-images.githubusercontent.com/4182469/52998243-2160c300-3423-11e9-9e28-d90422e7d27c.PNG)

PDF-Creation:
![lookslike](https://user-images.githubusercontent.com/4182469/52998273-30e00c00-3423-11e9-8277-e07cdb474500.PNG)

**Comment by dkehne** [comment]
The url to test it in our system is https://integreat.app/deepltest/ar/xxxxxxxxxxxxxxxxxx

**Comment by svenseeberg** [comment]
Please note: the Icons are images and not UTF-8 characters.

**Comment by svenseeberg** [comment]
The alignment of Icons can be fixed by adding a `float: right;` property.

**Comment by svenseeberg** [comment]
This problem does not exist in general. With carefully crafted text, the problems do not occur. Even floating images to the right does work by just using the RTL button.
![screenshot from 2019-03-05 13-30-01](https://user-images.githubusercontent.com/15197000/53805576-cc589d00-3f4a-11e9-872d-538426448fbc.png)

**Comment by svenseeberg** [comment]
There are also issues when displaying the text in the web app. For example the telephone number line source code is `<img class="alignnone wp-image-584" src="phone-handset.png" width="15" height="15" /> <a href="tel:+497071560325">07071-560325</a> XXXX <a href="tel:+497071560311">-11</a>`

AFAICT the Latin numbers should be displayed left-to-right as it should be in any left-to-right text. However the XXXX between both numbers is out on the left in the web app. The web app does display the full number first and then `07071-560325` and then `-11`. The PDF is doing this the wrong way.

I think that this example page is totally borked. In general, we should take care that Latin characters should be moved out into separate paragraphs which ideally use left-to-right text. There are examples where some left-to-right numbers do work with right-to-left text (see my previous post).

Fixing the PDF generation out of scope for this issue tracker and would have to be fixed upstream in https://github.com/mpdf/mpdf and also our https://github.com/Integreat/web-app

**Comment by svenseeberg** [comment]
Yet another interesting fact: when wrapping the phone number line into its own `<p dir="rtl">` paragraph, the PDF resembles the web app result:
![screenshot from 2019-03-05 14-05-21](https://user-images.githubusercontent.com/15197000/53807444-dc26b000-3f4f-11e9-86e3-a79e25111291.png)

**Comment by svenseeberg** [comment]
And one more problem when comparing source code and web app result:
`<strong>XXXXXXXXXXXXXXX XXXXXXXX X.X.</strong>` results in **.XXXXXXXXXXXXXXX XXXXXXXX X.X**
