### ISSUE TITLE
Comments: Page always jumps to the top wenn details are folded out

### ISSUE THREAD

**Issue by FritjofK** [Integreat/cms#937]
**Describe the bug**
Page jumps back to the top when details of comments are folded out. 

**To Reproduce**

"Testumgebung": Got to Comments (where feedback arrives) and scroll down the page and fold out details of a comment. It folds out but the page jumps back to the top. Not very intuitive. 

Tested in Firefox and Chrome

**Comment by svenseeberg** [comment]
@timoludwig I guess that this is Wordpress default behaviour and has nothing to do with out code or does it?
