### ISSUE TITLE
Slightly adjust feedback-endpoint

### ISSUE THREAD

**Issue by Schedulaar** [Integreat/cms#974]
The feedback endpoint for specific pages (like categories, events, etc.) should allow `permalink` to have a leading opening parantheses (like the pdf-endpoint allows), for example:
```json
  permalink: "/augsburg/en/family"
```
instead of `augsburg/en/family`

**Comment by svenseeberg** [comment]
@timoludwig in your commit you're handling the leading slash. Are quotes also being handled? I guess that is what @Schedulaar was referring to?

**Comment by timoludwig** [comment]
I didn't open a pull request yet, because I was unsure if this beaks anything on our live apps.
Strictly speaking, this change does not _allow_ the permalink to have a leading slash, but _requires_ it. I think I have to provide a solution which works for both cases.

**Comment by svenseeberg** [comment]
Okay, what about first stripping leading and trailing slashes, then add one leading slash?

**Comment by timoludwig** [comment]
Ok, so the inbuilt wordpress function (probably manipulated by WPML) does only work _without_ leading slashes for some pages. Thus, removing leading slashes if present is sufficient to solve the issue.
